### ISSUE TITLE
adjust all HTTP requests to follow Hadley's advice

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/soilDB#10]
https://cran.r-project.org/web/packages/httr/vignettes/api-packages.html

**Comment by dylanbeaudette** [comment]
Further ideas on how to cache / check for pre-downloaded data:

https://gist.github.com/Nowosad/465aff1e2c83c734170572d64fc001e7

**Comment by brownag** [comment]
This has mostly been addressed after many iterations of finding unskipped tests/examples that break on CRAN or when various web services go down.
