### ISSUE TITLE
limits on bounding box queries fetchKSSL

### ISSUE THREAD

**Issue by brownag** [ncss-tech/soilDB#103]
fetchKSSL allows arbitrarily large bounding boxes for fetching pedon laboratory data.

It is possible to specify a bounding box so large that the HTTP request fails with error code 500:

>  f <- fetchKSSL(bbox = c(-84,  38, -89,  42))
> Error in download.file(url = hz.url, destfile = tf.hz, mode = "wb", quiet = TRUE) : 
>   cannot open URL 'https://casoilresource.lawr.ucdavis.edu/soil_web/kssl/query.php?gzip=1&what=horizon&bbox=-84,38,-89,42'

Possibly needs reworking on the SoilWeb side to return a more informative error message when a certain number of records / result data size is exceeded within the extent of interest. 

Currently requests that result up to ~12MB in size (~2000 pedons) seem to go through without a hitch.

**Comment by dylanbeaudette** [comment]
Oddly enough that request works fine in a WWW browser.

This is resource limitation at the PHP interpreter level. There is no simpler way to estimate the size of the data returned before the attempt is made, so I can't really think of a decent heuristic at this time. You get the same kind of results with SDA, however a nice resource limitation error is thrown.

However, there is now different issue: `fetchKSSL(bbox=...)` was broken in my recent re-write.

**Comment by dylanbeaudette** [comment]
For the record:

```r
library(soilDB)
library(aqp)


# works as expected
x <- fetchKSSL(bbox = c(-121, 38, -121.5, 38.5))

# big one, ~16 Mb
x <- fetchKSSL(bbox = c(-84, 38, -89, 42))

# not all combinations in arguments makes sense, some requests result in NULL
x <- fetchKSSL(series=c('amador', 'sites'), mlra=c('18', '22A', '212'))

# no results because all requests include the BBOX
fetchKSSL(series=c('amador', 'sites'), mlra=c('18', '22A'), bbox = c(-121, 38, -121.5, 38.5))
```

**Comment by brownag** [comment]
This is great. 

This issue was especially a problem before your work vectorizing fetchKSSL. 

Clearly there were a couple bugs left to smash after that -- but now the combination of vectorization + options will allow for large queries to be completed in a single call. Which is a far better outcome than just printing an error saying "TOO BIG!!!"
