### ISSUE TITLE
namespace conflict with FedData::SDA_query()

### ISSUE THREAD

**Issue by brownag** [ncss-tech/soilDB#105]
It appears that there is an identically named function `SDA_query()` in the package `FedData`. It does not work in the same manner as `soilDB`

**Comment by dylanbeaudette** [comment]
Thanks for finding this. Examples for an issue on the FedData page.

```r
q <- "SELECT 
component.mukey, cokey, comppct_r, compname, taxclname, 
taxorder, taxsuborder, taxgrtgroup, taxsubgrp
FROM legend
INNER JOIN mapunit ON mapunit.lkey = legend.lkey
LEFT OUTER JOIN component ON component.mukey = mapunit.mukey
WHERE legend.areasymbol = 'CA113' ;"

x <- soilDB::SDA_query(q)
x.fd <- FedData::SDA_query(q)
```

Issues:
   * SDA errors not returned
   * column types are all character
   *  only first row returned
   * multiple tables not returned, should be a list
   * error when SDA result is 0 records, should be NULL

**Comment by bocinsky** [comment]
Hi all! Sorry, did this before I really understood how namespaces worked, and I thought it wasn't exported, anyway. I've changed the function name in FedData to avoid this issue, and will submit to CRAN once I have pushed a critical mass of changes.

**Comment by dylanbeaudette** [comment]
Thanks @bocinsky, this is big help. Many of our staff are familiar with loading packages and getting work done but namespace conflicts can be show-stoppers. Is there anything we can do to make `soilDB::SDA_query` more useful to the `FedData` package?

**Comment by bocinsky** [comment]
Hey! I'm working on a couple of pull requests for `soilDB::SDA_query` that would remove the read/write operations, which can have quite a bit of overhead for large queries. Let me start by filing two issues (one for the JSON request in `SDA_query`, one for the `.post_process_SDA_result_set` function), and then see what I can do.

**Comment by dylanbeaudette** [comment]
Thanks. All working well after merging those 2 pull requests. We appreciate your suggestions and I learned something new: `type.convert`.
