### ISSUE TITLE
Avoid writing (then reading) JSON form at the start of `SDA_query`

### ISSUE THREAD

**Issue by bocinsky** [ncss-tech/soilDB#106]
Currently, the `SDA_query` function writes a JSON form to a temporary file, then reads the form as part of the `httr::POST` request. Instead, we can just define the query within the request:
```{r}
  # submit request
  r <- httr::POST(url = "https://sdmdataaccess.sc.egov.usda.gov/tabular/post.rest",
                  body = list(query = q,
                              format = "JSON+COLUMNNAME"),
                  encode = "form")
```

**Comment by dylanbeaudette** [comment]
Good idea. Not sure why we wrote to a file first. This is much simpler. Tested and appears to work well.
