### ISSUE TITLE
soilDB removed from CRAN

### ISSUE THREAD

**Issue by brownag** [ncss-tech/soilDB#111]
We found out today that soilDB got removed from CRAN for noncompliance -- the issue had to do with documentation examples that used internet resources which were timing out.

Previously, all internet-based calls were wrapped with \dontrun{} -- but there apparently were issues with this code being run during package checking procedure on CRAN side. This is a problem because aqp depends on soilDB for some of its examples -- so aqp is also at risk of being archived on CRAN.

Here is a link to the cached CRAN check results that show the culprit was a call to fetchOSD in the documentation file for OSD_query. 

fetchOSD was timing out (>10000ms) on the r-patched-solaris-x86 platform. The package was removed the day after this check (10/28/2019).

Excerpt -- https://pastebin.com/w54i0LbG -- failing on example code in OSD_query.Rd:
```
    > x <- fetchOSD(s$series, extended = TRUE, colorState = 'dry')
    Error in open.connection(con, "rb") :
     Timeout was reached: [casoilresource.lawr.ucdavis.edu] Resolving timed out after 10000 milliseconds
```

I've replaced all relevant \dontrun with \donttest, as this is the preferred convention per CRAN maintainers. I don't know that this will resolve the issue as \dontrun should have prevented this from happening in the first place.

**Comment by dylanbeaudette** [comment]
Thanks Andrew. I suspect that I hadn't heard anything about the pending doom because the DESCRIPTION file still listed my email in the old .ca.usda.gov format. Not sure if those are still forwarded.

I'll work on a new soilDB release ASAP.

**Comment by dylanbeaudette** [comment]
This is giving me trouble, something in the man pages is cross-linked or ???

{{{
Undocumented arguments in documentation object 'fetchNASISWebReport'
     'drop.unused.levels'
   
   Documented arguments not in \usage in documentation object 'fetchNASIS':
     'drop.unused.levels'
}}}

**Comment by dylanbeaudette** [comment]
Another one:

```
W  checking for unstated dependencies in examples (943ms)
   '::' or ':::' imports not declared from:
     'gridExtra' 'viridis'
   'library' or 'require' calls not declared from:
     'RCurl' 'XML' 'ggplot2' 'gridExtra'
```

**Comment by brownag** [comment]
Quoted from http://r-pkgs.had.co.nz/check.html
> 
>     Checking for unstated dependencies in examples. If you use a package only for an example, make sure it’s listed in the Suggests field. Before running example code that depends on it, test to see if it’s available with `requireNamespace("pkg", quietly = TRUE)`:
```

    #' @examples
    #' if (requireNamespace("dplyr", quietly = TRUE)) {
    #'   ...
    #' }

```

**Comment by dylanbeaudette** [comment]
Thanks @brownag. I've just made those changes and working on a build for submission. We can improve the documentation on the next release.

**Comment by brownag** [comment]
> 
> 
> -----Original Message-----
> From: ligges@statistik.tu-dortmund.de <ligges@statistik.tu-dortmund.de> 
> Sent: Thursday, November 7, 2019 8:48 AM
> To: Beaudette, Dylan - NRCS, Sonora, CA <dylan.beaudette@usda.gov>
> Cc: CRAN-submissions@R-project.org
> Subject: [CRAN-pretest-publish] CRAN submission soilDB 2.4.1
> 
> Dear maintainer,
>  
> thanks, package soilDB_2.4.1.tar.gz is on its way to CRAN.
>  
> Best regards,
> CRAN teams' auto-check service
>
