### ISSUE TITLE
fetchKSSL nonunique labsampnum

### ISSUE THREAD

**Issue by brownag** [ncss-tech/soilDB#117]
Discovered that some horizons in the KSSL database have the same labsampnum. Some of the duplicate numbered horizons have the same data -- others have different data, missing calculations. etc.

This causes some problems with the code I added recently to automatically use labsampnum as unique horizon ID. fetchKSSL will fail (after being caught by one of our errors)

> 
> > fetchKSSL(mlra="1")
> Error: target ID name not unique

Affected labsampnums (420 out of 268558 horizon in KSSL db):
`01N00629,01N00636,01N00637,01N00638,01N00639,01N00659,01N00660,01N02042,01N02043,01N02044,01N05004,01P00393,02N00253,02N00254,02N00262,02N00263,02N00264,02N00265,02N00266,02N00267,02N00268,02N00269,02N00270,02N00271,02N00272,02N00273,02N00274,02N00275,02N00276,02N00277,02N00278,02N00279,02N00280,02N00452,02N00453,02N00455,02N00456,02N00457,02N00458,02N00459,02N02675,02N02676,02N02677,02N02678,02N02679,02N02680,02N02681,02N02682,02N02683,02N02684,02N02685,02N02686,02N02687,02N02688,02N02689,02N02690,02N02691,02N02692,02N02693,02N02694,02N02695,02N02696,02N02697,02N02698,02N02699,02N02700,02N02701,02N02702,02N02703,02N02704,03N00471,03N00982,03N00989,03N00991,03N00999,03N01000,03N01001,03N01008,03N01009,03N01010,03N01017,03N01018,03N01019,03N01027,03N01028,03N01029,03N01035,03N01036,03N01037,03N01043,03N01045,03N03434,03N03435,03N03436,03N03437,03N03438,03N03443,03N03444,03N03445,03N03446,03N03447,03N03448,03N03449,03N03450,03N03451,03N03452,03N03453,03N03454,03N03455,03N03457,03N03463,03N03464,03N03465,03N03466,03N03467,03N03468,03N03469,03N03470,03N03471,03N03472,03N03473,03N03474,03N03475,03N03476,03N03480,03N03481,03N03482,03N03483,03N03484,03N03485,03N03486,03N03487,03N04686,03N04687,03N04689,03N04691,04N06529,04N06530,04N06531,04N06532,04N06533,04N06534,04N06535,04N06536,04N06537,04N06538,04N06539,06N02275,06N02276,06N02281,06N04346,06N04347,06N04733,06N04734,06N04735,06N04736,06N04737,06N04738,06N04739,06N04740,06N04741,06N04742,06N04743,06N04744,06N04745,06N04746,06N04747,06N04748,06N04749,06N04750,06N04751,06N04752,06N04753,06N04754,06N04755,06N04756,06N04757,06N04758,06N04759,06N04760,06N04761,06N04762,06N04763,06N04764,06N04765,06N04766,06N04767,06N04768,06N04769,06N04770,06N04771,06N04772,06N04773,06N04774,06N04775,06N04776,06N04777,06N04778,06N04779,06N04780,06N04781,06N04782,06N04783,06N04784,06N04785,06N04786,06N04787,06N04788,07N00493,07N00494,07N00495,07N00496,07N00497,07N00498,07N00499,07N00501,07N00502,07N00503,07N00504,07N00505,07N00506,07N00507,11N03447,11N03448,11N03449,11N03450,11N03451,11N03452,11N03453,11N03454,40A15105,40A15106,40A15107,40A15108,40A15109,40A15110,40A15111,40A15112,40A15300,40A15301,40A15302,40A15303,40A15304,40A15305,40A15306,40A15307,40A15308,40A15309,40A15310,40A15311,40A15312,40A15313,40A15314,40A15316,40A15317,40A15318,40A15319,40A15320,40A15321,40A15322,40A15358,40A15359,40A15360,40A15361,40A15362,40A15363,40A15364,40A15365,40A15622,40A15623,40A15624,40A15625,40A15626,40A15627,40A15629,40A15630,40A15631,40A15632,40A15633,40A15634,40A15635,40A15636,40A15637,40A15638,40A15639,40A15640,40A15641,40A15642,40A15643,40A15644,40A15645,40A15649,40A15650,40A15651,40A15652,40A15653,40A15654,40A15655,40A15656,40A15657,40A15658,40A15659,40A15660,40A15661,40A15662,40A15663,40A15664,40A15665,40A15667,40A15668,40A15669,40A15670,40A15671,40A15672,40A15673,40A15674,40A15675,40A15676,40A15677,40A15678,40A15679,40A15680,40A15681,40A15682,40A15683,40A15684,40A15685,40A15686,40A15687,40A15688,40A15689,40A15690,40A15691,40A15692,40A15695,40A15696,40A15697,40A15698,40A15699,40A15700,40A15701,40A15702,40A15703,40A15704,40A15705,40A15706,40A15707,40A15708,40A15709,40A15710,40A15711,40A15712,40A15713,40A15714,69C00442,75C00125,75C00126,79P00112,79P00113,79P00114,79P00115,79P00116,79P00117,79P00118,79P00119,79P00120,79P00121,79P00123,79P00124,79P00125,79P00126,79P00127,79P00128,79P00129,79P00131,79P00132,79P00133,79P00134,79P00135,79P00136,79P00137,79P00138,79P00140,79P00141,79P00142,79P00143,79P00144,79P00145,79P02292,81P04207,81P04208,81P04209,82P03107,82P03108,82P03109,82P03110,82P03111,82P03112,82P03113,82P03125,82P03126,82P03127,82P03128,82P03129,82P03130,82P03131,86P05440,86P05441,86P05442,86P05443,86P05445,86P05446,86P05447,86P05448,86P05449,86P05450,88P03651,88P03652,92P02055,95P04460`

**Comment by brownag** [comment]
2bc4e63 patches fetchKSSL to have original behavior of 1:n sequence of integers as unique ID, generated by SPC constructor.

**Comment by dylanbeaudette** [comment]
Thanks for finding / addressing this issue. There are very few record IDs that we can trust, only those that are auto-generated by NASIS or the SSURGO export process. I should have mentioned that labsampnum was **manually** maintained and any kind of (intentional) pedon duplication or data-entry errors could lead to this.
