### ISSUE TITLE
fetch NASIS not working anymore?

### ISSUE THREAD

**Issue by phytoclast** [ncss-tech/soilDB#119]
I attempted to get pedons from my local NASIS database using code that worked the previous day:
fp <-  fetchNASIS(from = 'pedons', SS=FALSE, rmHzErrors=FALSE)
or
fp <-  fetchNASIS_pedons(SS=FALSE, rmHzErrors=FALSE)

But neither picks up any pedons. It appears to have rejected all the pedons despite settingrmHzErrors=FALSE.  Previously, it rejected only a small portion without setting this parameter to false. Otherwise I get 14508 sites from the following:
fp <- get_site_data_from_NASIS_db()

I had updated soilDB package yesterday from the CRAN site and then tried from Github after it failed. I don't know which version of soilDB I had before. 

Here's what it displays while running through the function:
-> QC: some fragsize_h values == 76mm, may be mis-classified as cobbles [2265 / 87278 records]
Error in seq_len(n_y) : 
  argument must be coercible to non-negative integer
In addition: Warning messages:
1: some records are missing rock fragment volume, these have been removed 
2: fragment volume >= 100%
phiid:
169882
3434526
6457722
4795915
1342845
1343973
1394664
1394698
1613346
1616199
1715626
1835912
1954923
1954924
1954935
1954936
1954937
2648833
2649275
2649286
2649297 
3: In seq_len(n_y) : first element used of 'length.out' argument

**Comment by brownag** [comment]
This is probably related to the specific input data in your local. fetchNASIS is passing internal tests and is working on my machine without the error you are experiencing. 

If you run this code and send me the output file @ andrew.g.brown@usda.gov I can try to reproduce your error.

```
write(paste0(unique(as.numeric(soilDB::get_site_data_from_NASIS_db(SS = FALSE)$siteiid)), collapse=','), file="bad_siteids.txt")
```

Running fetchNASIS with SS=FALSE is a bit less well-tested/potentially risky. It is possible there could be "orphan" records in some of the child tables that are interfering with the flattening steps that fetchNASIS does while making SPCs. For the most part fetchNASIS should be robust to that sort of thing but it is always possible that there could be something weird -- it only takes one pedon out of the set to error out and cause a problem. 

The way to check that it's not related to incomplete pedon records would be to clear your local DB and requery from National to ensure you have the full data structure. Or, query the desired data into your SS and run with default SS argument.

**Comment by phytoclast** [comment]
Slightly different error on this run:
> fp <-  fetchNASIS(from = 'pedons', SS=FALSE, rmHzErrors=FALSE)
multiple horizontal datums present, consider using WGS84 coordinates (x_std, y_std)
NOTICE: multiple `labsampnum` values / horizons; see pedon IDs:
98IN045006,F2008MI121016,F2010MI117001,F2010MI117008,S07MI121014,S07MI139011,S08MI139004,S1968MI057002,S1970IN141001,S1978MI085002,S1979MI081002,S1979MI081005,S1979MI107004,S1980MI073005,S1980MI073006,S1980MI081002,S1980MI081003,S1980MI081007,S1992IN035011,S1994IN035005,S1994IN035005a,S1994IN039021,S1994IN039022,S1994IN039023,S2001MI101005,S2007MI139011,S2009MI063001,S2009MI123002,S2010MI117001,S2010MI117008,S2011MI117102,S2011OH003117,S2012IN003002,S2013MI091028,S2013MI149001,S2013MI161021,S2014MI067001A,S2014MI067001B,S2014MI067001C,S2014MI067001D,S2014MI067001E,S2014MI081001A,S2014MI081001B,S2014MI081001C,S2014MI081001D,S2014MI081001E,S2014MI117001A,S2014MI117001B,S2014MI117001C,S2014MI117001D,S2014MI117001E,S2014MI123001A,S2014MI123001B,S2014MI123001C,S2014MI123001D,S2014MI123001E,S2015MI015001A,S2015MI015001B,S2015MI015001C,S2015MI015001D,S2015MI015001E,S2015MI037001A,S2015MI037001B,S2015MI037001C,S2015MI037001D,S2015MI037001E,S2015MI037002A,S2015MI045001A,S2015MI045001B,S2015MI045001C,S2015MI045001D,S2015MI045001E,S2015MI045002A,S2015MI045002B,S2015MI045002C,S2015MI045002D,S2015MI045002E,S2015MI107001A,S2015MI107001B,S2015MI107001C,S2015MI107001D,S2015MI107001E,S2015OH065002,S2015OH065003,S2015OH109001,S2016OH065004,S2017MI127001
mixing dry colors ... [103 of 4911 horizons]
CIE2000 comparisons require `farver` version 2.0.2 or greater, using Euclidean distance in CIELAB insteadFALSE
mixing moist colors ... [4371 of 69041 horizons]
CIE2000 comparisons require `farver` version 2.0.2 or greater, using Euclidean distance in CIELAB insteadFALSE
-> QC: some fragsize_h values == 76mm, may be mis-classified as cobbles [2265 / 87278 records]
-> QC: some huartsize_h values == 76mm, may be mis-classified as cobbles [1 / 81961 records]
replacing missing lower horizon depths with top depth + 1cm ... [592 horizons]
top/bottom depths equal, adding 1cm to bottom depth ... [326 horizons]
Error: target ID name not unique
In addition: Warning messages:
1: some records are missing rock fragment volume, these have been removed 
2: fragment volume >= 100%
phiid:
169882
3434526
6457722
4795915
1342845
1343973
1394664
1394698
1613346
1616199
1715626
1835912
1954923
1954924
1954935
1954936
1954937
2648833
2649275
2649286
2649297 
3: some records are missing artifact volume, these have been removed

**Comment by brownag** [comment]
You've got a warning and an error -- they are related to automatic join of lab data into horizon table. 

First is this: "NOTICE: multiple labsampnum values / horizons; see pedon IDs:"

soilDB automatically tries to join the Pedon Horizon Sample table into the horizon table when it builds the SPC. If there is a many to 1 relationship between phsample and phorizon, this will duplicate those particular horizons in the horizon table.

This typically would be considered a horizon error -- since you usually set rmHzErrors=FALSE you might not notice the duplication/overlapping horizons. Since aqp 1.17 we have enforced horizon ID uniqueness constraints -- so the allowable overlapping horizons must have unique horizon IDs.

That is your second error "Error: target ID name not unique" is from the internal setter of the unique horizon ID. This should probably be a little more informative, and I can update it so that it assigns a new unique ID, rather than try to use the duplicate. 

Give me a moment and I'll have some fixes for you to test.

**Comment by phytoclast** [comment]
My main goal was to identify nearest user_pedon_ids to a set of GPS points, so I didn't care if some records had horizon errors, but only that data existed. I think lab pedons get duplicated, because the lab's copy of the pedon is protected from further edits.

**Comment by brownag** [comment]
Thanks for checking that, Greg. Sorry for delay on the fix I also found some bugs in fragment and artifact extended data that needed straightening out. 

Now when `rmHzErrors=FALSE` the expectation that `phiid` is unique is relaxed. A QC warning is issued in the console when you call fetch NASIS.

```
-> QC: duplicate horizons are present with rmHzErrors=FALSE! defaulting to `hzID` as unique horizon ID.
```

You should install the latest versions of aqp and soilDB off of GitHub to get my changes

```
remotes::install_github('ncss-tech/aqp', dependencies=F, build=F)
remotes::install_github('ncss-tech/soilDB', dependencies=F, build=F)
```

Let me know if it works for you

**Comment by dylanbeaudette** [comment]
Thanks @brownag for the quick diagnosis and fixes. @phytoclast: a custom query to the `site` table for IDs and coordinates might be a useful follow-up.

**Comment by brownag** [comment]
![image](https://user-images.githubusercontent.com/20842828/72561332-d3845300-385d-11ea-9b2d-9a2b249b6e0e.png)

Here is a screenshot of the type of offending data in NASIS. If the input data were cleaned up, far fewer pedons would have uniqueness issues after joining in `phsample`.

**Comment by phytoclast** [comment]
I am sorry, I reinstalled those packages, and still get the error and no pedons load.

> fp <-  fetchNASIS_pedons(SS=FALSE, rmHzErrors=FALSE)
multiple horizontal datums present, consider using WGS84 coordinates (x_std, y_std)
NOTICE: multiple `labsampnum` values / horizons; see pedon IDs:
98IN045006,F2008MI121016,F2010MI117001,F2010MI117008,S07MI121014,S07MI139011,S08MI139004,S1968MI057002,S1970IN141001,S1978MI085002,S1979MI081002,S1979MI081005,S1979MI107004,S1980MI073005,S1980MI073006,S1980MI081002,S1980MI081003,S1980MI081007,S1992IN035011,S1994IN035005,S1994IN035005a,S1994IN039021,S1994IN039022,S1994IN039023,S2001MI101005,S2007MI139011,S2009MI123002,S2010MI117001,S2010MI117008,S2011MI117102,S2011OH003117,S2012IN003002,S2013MI091028,S2013MI149001,S2013MI161021,S2014MI067001A,S2014MI067001B,S2014MI067001C,S2014MI067001D,S2014MI067001E,S2014MI081001A,S2014MI081001B,S2014MI081001C,S2014MI081001D,S2014MI081001E,S2014MI117001A,S2014MI117001B,S2014MI117001C,S2014MI117001D,S2014MI117001E,S2014MI123001A,S2014MI123001B,S2014MI123001C,S2014MI123001D,S2014MI123001E,S2015MI015001A,S2015MI015001B,S2015MI015001C,S2015MI015001D,S2015MI015001E,S2015MI037001A,S2015MI037001B,S2015MI037001C,S2015MI037001D,S2015MI037001E,S2015MI037002A,S2015MI045001A,S2015MI045001B,S2015MI045001C,S2015MI045001D,S2015MI045001E,S2015MI045002A,S2015MI045002B,S2015MI045002C,S2015MI045002D,S2015MI045002E,S2015MI107001A,S2015MI107001B,S2015MI107001C,S2015MI107001D,S2015MI107001E,S2015OH065002,S2015OH065003,S2015OH109001,S2016OH065004,S2017MI127001
mixing dry colors ... [97 of 4412 horizons]
CIE2000 comparisons require `farver` version 2.0.2 or greater, using Euclidean distance in CIELAB insteadFALSE
mixing moist colors ... [4107 of 61566 horizons]
CIE2000 comparisons require `farver` version 2.0.2 or greater, using Euclidean distance in CIELAB insteadFALSE
-> QC: some fragsize_h values == 76mm, may be mis-classified as cobbles [2159 / 79033 records]
Error in `[.data.frame`(y, by) : undefined columns selected
In addition: Warning messages:
1: some records are missing rock fragment volume, these have been removed 
2: fragment volume >= 100%
phiid:
169882
3434526
6457722
4795915
1342845
1343973
1394664
1394698
1613346
1616199
1715626
1835912
1954923
1954924
1954935
1954936
1954937
2648833
2649275
2649286
2649297 
3: all records are missing artifact volume (NULL). buffering result with NA. will be converted to zero if nullFragsAreZero = TRUE. 


The NASIS Query:
FROM site
INNER JOIN nasisgroup ON nasisgroup.grpiid=site.grpiidref AND  nasisgroup.group_name LIKE ? "NASIS Group Name, Use % for wildcard" 
INNER JOIN siteobs ON site.siteiid=siteobs.siteiidref AND siteobs.obsdate BETWEEN ? "Begin date" AND  ? "End date"
LEFT OUTER JOIN pedon ON siteobs.siteobsiid=pedon.siteobsiidref
WHERE site.latstddecimaldegrees BETWEEN ? "Minimum Latitude" AND  ? "Maximum Latitude" AND site.longstddecimaldegrees BETWEEN ? "Minimum Longitude" AND  ? "Maximum Longitude"

Wherein I select wildcard for groupname, dates between 01/01/1950 and 12/31/2019, and latitudes 40 to 45, and longitude between -87.5 and 83.5, downloading from site and pedon tables.
get_site_data_from_NASIS_db(SS=FALSE) retrieves 13433 sites.

**Comment by brownag** [comment]
Well, that is a different error at least. Investigating now.

**Comment by phytoclast** [comment]
A subset from 2011 onward returned results, so it is older records...

**Comment by brownag** [comment]
@phytoclast 

I ran your query for the full time range and lat/long interval. My result is a SPC with 13205 profiles in it.

```
> fp <- fetchNASIS(from = 'pedons', SS=FALSE, rmHzErrors=FALSE)
multiple horizontal datums present, consider using WGS84 coordinates (x_std, y_std)
NOTICE: multiple `labsampnum` values / horizons; see pedon IDs:
98IN045006,F2008MI121016,F2010MI117001,F2010MI117008,S07MI121014,S07MI139011,S08MI139004,S1968MI057002,S1970IN141001,S1978MI085002,S1979MI081002,S1979MI081005,S1979MI107004,S1980MI073005,S1980MI073006,S1980MI081002,S1980MI081003,S1980MI081007,S1992IN035011,S1994IN035005,S1994IN035005a,S1994IN039021,S1994IN039022,S1994IN039023,S2001MI101005,S2007MI139011,S2009MI063001,S2009MI123002,S2010MI117001,S2010MI117008,S2011MI117102,S2011OH003117,S2012IN003002,S2013MI091028,S2013MI149001,S2013MI161021,S2014MI067001A,S2014MI067001B,S2014MI067001C,S2014MI067001D,S2014MI067001E,S2014MI081001A,S2014MI081001B,S2014MI081001C,S2014MI081001D,S2014MI081001E,S2014MI117001A,S2014MI117001B,S2014MI117001C,S2014MI117001D,S2014MI117001E,S2014MI123001A,S2014MI123001B,S2014MI123001C,S2014MI123001D,S2014MI123001E,S2015MI015001A,S2015MI015001B,S2015MI015001C,S2015MI015001D,S2015MI015001E,S2015MI037001A,S2015MI037001B,S2015MI037001C,S2015MI037001D,S2015MI037001E,S2015MI037002A,S2015MI045001A,S2015MI045001B,S2015MI045001C,S2015MI045001D,S2015MI045001E,S2015MI045002A,S2015MI045002B,S2015MI045002C,S2015MI045002D,S2015MI045002E,S2015MI107001A,S2015MI107001B,S2015MI107001C,S2015MI107001D,S2015MI107001E,S2015OH065002,S2015OH065003,S2015OH109001,S2016OH065004,S2017MI127001
mixing dry colors ... [97 of 4413 horizons]
mixing moist colors ... [4104 of 61550 horizons]
-> QC: some fragsize_h values == 76mm, may be mis-classified as cobbles [2159 / 79020 records]
replacing missing lower horizon depths with top depth + 1cm ... [539 horizons]
top/bottom depths equal, adding 1cm to bottom depth ... [325 horizons]
-> QC: sites without pedons: use `get('sites.missing.pedons', envir=soilDB.env)` for related usersiteid values
-> QC: duplicate pedons: use `get('dup.pedon.ids', envir=soilDB.env)` for related peiid values
-> QC: duplicate horizons are present with rmHzErrors=FALSE! defaulting to `hzID` as unique horizon ID.
-> QC: horizon errors detected, use `get('bad.pedon.ids', envir=soilDB.env)` for related userpedonid values or `get('bad.horizons', envir=soilDB.env)` for related horizon designations
-> QC: pedons missing bottom hz depths: use `get('missing.bottom.depths', envir=soilDB.env)` for related pedon IDs
-> QC: equal hz top and bottom depths: use `get('top.bottom.equal', envir=soilDB.env)` for related pedon IDs
Warning messages:
1: some records are missing rock fragment volume, these have been removed 
2: fragment volume >= 100%
phiid:
169882
3434526
6457722
4795915
1342845
1343973
1394664
1394698
1613346
1616199
1715626
1835912
1954923
1954924
1954935
1954936
1954937
2648833
2649275
2649286
2649297 
3: some records are missing artifact volume, these have been removed 
4: all records are missing artifact volume (NULL). buffering result with NA. will be converted to zero if nullFragsAreZero = TRUE. 
> length(fp)
[1] 13205
```

I would try installing from GitHub again -- but first open up a fresh R session (Ctrl+Shift+F10) -- then, inspect the console log make sure you don't have any errors during the install.

**Comment by phytoclast** [comment]
I refreshed the R session, and reinstalled from Github. Everything seems to have imported from NASIS fine, including the older records. Thanks!
