### ISSUE TITLE
seriesExtentAsGmap

### ISSUE THREAD

**Issue by brownag** [ncss-tech/soilDB#123]
`seriesExtentAsGmap` is broken and cannot be fixed since we need an API key.

Google Maps API returns the following error message: 

> The Google Maps Platform server rejected your request. You must use an API key to authenticate each request to Google Maps Platform APIs. For additional information, please refer to http://g.co/dev/maps-no-account

Two options I see:

- Consider alternate sources of basemap data to make map
- Provide argument to supply user-specified API key

**Comment by brownag** [comment]
Had to remove example from seriesExtent.Rd -- fix example when this issue is resolved.

**Comment by dylanbeaudette** [comment]
Good catch. That function is never going to work again, removing it. I'll be sure to remove it from any related tutorials.
