### ISSUE TITLE
multiple sensors -- fetchSCAN

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/soilDB#14]
There are some SCAN/SNOTEL stations with multiple (above-ground) sensors per sensor prefix. For example:
```r
library(soilDB)
m <- SCAN_sensor_metadata(site.code=c(482,613))
m[, 1:3]
```
```
   site.code      Label                    Element
1        482   WTEQ.I-1      Snow Water Equivalent
2        482   WTEQ.I-2      Snow Water Equivalent
3        482   PREC.I-1 Precipitation Accumulation
4        482   PREC.I-2 Precipitation Accumulation
5        482   TOBS.I-1   Air Temperature Observed
6        482   TOBS.I-2   Air Temperature Observed
7        482   TOBS.I-3   Air Temperature Observed
8        482   TMAX.D-1    Air Temperature Maximum
9        482   TMIN.D-1    Air Temperature Minimum
```

As of ab70a989fa8c9c86d495e3d3f1e4e5a9921caa59 `fetchSCAN()` will issue a message and then naively use the **first** sensor.

A better solution would require significant changes to `fetchSCAN()` and / or working with SCAN admins.

**Comment by dylanbeaudette** [comment]
There are [apparently](https://wcc.sc.egov.usda.gov/nwcc/site?sitenum=2196) some SCAN sites with multiple below-ground sensors too.

**Comment by dylanbeaudette** [comment]
Several possible solutions:

 1. include all sensors and add an ID
 2. keep the first sensor
 3. keep the sensor with the most data associated with it (across all years)

**Comment by brownag** [comment]
```
## example of multiple versions of the below-ground sensors
## due to sensor repair, replacement, upgrades, loss of function, ???
```

RE: site 2196

I am pretty sure that these are actually duplicate below-ground sensors. Both sensors are active as of 2021. The values are very similar but not identical. 

``` r
library(soilDB)

f <- fetchSCAN(2196, 2021)
#> multiple sensors per depth [site 2196] STO.I_2, STO.I_4, STO.I_8, STO.I_20, STO.I_40, STO.I-2_2, STO.I-2_4, STO.I-2_8, STO.I-2_20, STO.I-2_40
#> 7301 records (0.33 Mb transferred)
f1 <- subset(f$STO, f$STO$sensor.id == "STO.I_2")
f2 <- subset(f$STO, f$STO$sensor.id == "STO.I-2_2")

plot(f1$value~f1$Date, type="l", lty = 2)
lines(f2$value~f2$Date, lty = 3)
```

![](https://i.imgur.com/ndfbwID.png)

``` r
summary(lm(f1$value ~ f2$value))
#> 
#> Call:
#> lm(formula = f1$value ~ f2$value)
#> 
#> Residuals:
#>       Min        1Q    Median        3Q       Max 
#> -0.214075 -0.051135 -0.000856  0.044210  0.185177 
#> 
#> Coefficients:
#>               Estimate Std. Error t value Pr(>|t|)    
#> (Intercept) -0.0991436  0.0058147  -17.05   <2e-16 ***
#> f2$value     1.0093109  0.0004542 2222.12   <2e-16 ***
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> 
#> Residual standard error: 0.06935 on 363 degrees of freedom
#> Multiple R-squared:  0.9999, Adjusted R-squared:  0.9999 
#> F-statistic: 4.938e+06 on 1 and 363 DF,  p-value: < 2.2e-16
```

**Comment by dylanbeaudette** [comment]
Good, those are simpler to account for. Keep in mind those notes and this issue has to do with all of the potential reasons for multiple sensors / type / depth. These were examples to follow-up on.

**Comment by brownag** [comment]
Do you have an example site ID where a sensor was replaced? I'd like to see one of those

**Comment by brownag** [comment]
An example might be `sitenum=783`

**Comment by brownag** [comment]
Could we close this issue by just opting to return all sensor data (above ground included)? I think it would be valuable to have aggregation methods, but for `fetchSCAN()` probably a more general approach of just returning available data makes the most sense.

**Comment by dylanbeaudette** [comment]
Yeah, that is fine. I haven't looked at this part of the code recently, but I think that this means we keep the current behavior of returning all data and leaving aggregation to a follow-up step. This will give more control and prevent additional complexity in `fetchSCAN()`.

**Comment by brownag** [comment]
I believe the above ground sensor data is only the first sensor, but below ground returns all sensors. 

It is a simple fix to return the full set, just remove `d.cols <- d.cols[1]` and call it good. Can still issue the message "multiple sensors per site".

https://github.com/ncss-tech/soilDB/blob/f608f5f44b01befbaf9988c453f7e4f13405f06e/R/fetchSCAN.R#L238-L246
