### ISSUE TITLE
sort out CRS warnings in seriesExtent

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/soilDB#144]
This has to do with the evolution of proj4 syntax in `sp`, `rgdal`, etc..

```
Warning message:
In proj4string(x) : CRS object has comment, which is lost in output
```

```
Warning message:
In showSRID(uprojargs, format = "PROJ", multiline = "NO") :
  Discarded datum Unknown based on GRS80 ellipsoid in CRS definition,
 but +towgs84= values preserved
```

Generate warnings with this test.
```r
# required packages
library(soilDB)
library(sp)
library(raster)
library(rgdal)

# specify a soil series name
s <- 'magnor'

# return as SpatialPolygonsDataFrame
x <- seriesExtent(s, type = 'vector')
# return as raster
y <- seriesExtent(s, type = 'raster')

# note that CRS are different
proj4string(x)
projection(y)

# transform vector representation to CRS of raster
x <- spTransform(x, CRS(projection(y)))

# graphical comparison
par(mar = c(1, 1 , 1, 3))
plot(y, axes = FALSE)
plot(x, add = TRUE)
```

**Comment by brownag** [comment]
To mute warnings of possible GDAL/OSR exportToProj4() degradation, use `options("rgdal_show_exportToProj4_warnings"="none")` before loading rgdal. For tests in aqp affected by these same warnings and comments, I have generally been wrapping with `expect_warning` as needed. This requires "awareness" of the version of {rgdal} being used.

**Comment by dylanbeaudette** [comment]
This has to do with the extent grids being assigned the following (now old-style) CRS via proj4 string:

`+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=23 +lon_0=-96 +x_0=0 +y_0=0 +no_defs +a=6378137 +rf=298.257222101 +towgs84=0.000,0.000,0.000 +to_meter=1`

**Comment by dylanbeaudette** [comment]
An unambiguous proj4string needs to be used, it should be:

`+proj=aea +lat_0=23 +lon_0=-96 +lat_1=29.5 +lat_2=45.5 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs`

Useful reminders about datums / ellipsoids: https://vdatum.noaa.gov/docs/datums.html#nad83
