### ISSUE TITLE
experimental WCS interface to gSSURGO, gNATSGO, ISSR-800

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/soilDB#148]
Be sure to install the latest version of `soilDB` from github.

Demonstration of the new functionality here: https://github.com/ncss-tech/soilDB/blob/master/misc/WCS-SDA-example.R

A couple of major TODO items:
  * ~~double-check WCS parameters: BBOX, HEIGHT, WIDTH | RESX, RESY (ensure that data aren't resampled)~~
  * ~~consider WCS version 2.0 for more advanced query features and on-the-fly compression~~
  * ~~optimize source data (requests are processed very quickly but I don't know if this will scale)~~
  * ~~write convenience functions for setting BBOX from {sp} objects, in addition to a vector of `xmin,ymin,xmax,ymax`~~
  * ~~documentation~~
  * encode EPSG:6350 into source GeoTiff so that warnings aren't generated when loading in R
  * fully-abstracted "soil data aggregation engine" vs. wrangling SQL statements or ad hoc R code (#178)

Limitations:
  * gNATSGO / gSSURGO mukey grids are limited to 5000x5000 pixels, at 30m resolution this is about 1x1 degrees.
  * gNATSGO contains mukey values associated with new "raster soil surveys" which do not exist in SDA

It appears to work well using WCS 2.0.1 specifications and on-the-fly compression. At the limit of roughly 5000x5000 pixels, you can request about 1x1 degrees worth of data at 30m resolution, resulting in a ~3.5Mb GeoTiff.

![image](https://user-images.githubusercontent.com/624277/102660691-4cf08980-4130-11eb-8286-b96b2f527e49.png)
Apparent NODATA issues in the above image have been resolved.

**Comment by dylanbeaudette** [comment]
Last major TODO item: ensure that the data are no resampled when requested at 30m resolution. 

Ideas:
   * "adjust" BBOX to the nearest integer (AOI extent will not **exactly** match output extent)

**Comment by potash** [comment]
I realize that my comment on the related FedData thread is probably not the best place to share issues with this so I am pasting it here:

Thanks @dylanbeaudette ! I'm trying the [script](https://github.com/ncss-tech/soilDB/blob/master/misc/WCS-SDA-example.R) you referenced but I get the following error when running `(x <- mukey.wcs(db = 'gnatsgo', aoi = a))`: ` Error in CRS(value) : no arguments in initialization list`. Any ideas? 

```{r}
> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 10 (buster)

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/atlas/libblas.so.3.10.3
LAPACK: /usr/lib/x86_64-linux-gnu/atlas/liblapack.so.3.10.3

locale:
 [1] LC_CTYPE=en_US.UTF-8      
 [2] LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8      
 [8] LC_NAME=C                 
 [9] LC_ADDRESS=C              
[10] LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8
[12] LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics 
[3] grDevices utils    
[5] datasets  methods  
[7] base     

other attached packages:
[1] soilDB_2.5.9

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5       
 [2] cluster_2.1.0    
 [3] knitr_1.30       
 [4] xml2_1.3.2       
 [5] raster_3.4-5     
 [6] magrittr_2.0.1   
 [7] lattice_0.20-41  
 [8] rlang_0.4.9      
 [9] stringr_1.4.0    
[10] plyr_1.8.6       
[11] tools_4.0.3      
[12] rgdal_1.5-18     
[13] grid_4.0.3       
[14] data.table_1.13.2
[15] xfun_0.19        
[16] htmltools_0.5.0  
[17] yaml_2.2.1       
[18] digest_0.6.27    
[19] reshape2_1.4.4   
[20] codetools_0.2-16 
[21] curl_4.3         
[22] rlist_0.4.6.1    
[23] evaluate_0.14    
[24] rmarkdown_2.5    
[25] aqp_1.25         
[26] sp_1.4-4         
[27] stringi_1.5.3    
[28] compiler_4.0.3   
[29] reshape_0.8.8 
```

_Originally posted by @potash in https://github.com/ropensci/FedData/issues/53#issuecomment-754859007_

**Comment by dylanbeaudette** [comment]
@potash Thanks for the bug report, unfortunately I cannot replicate here with R 3.6.3 or 4.x. I'll give it a try on linux this afternoon and mac os tonight.

I suspect this has something to do with PROJ4 and major changes that have occurred over the last year. What does `traceback()` report?

**Comment by potash** [comment]
@dylanbeaudette thanks for looking into this, here is the traceback:

```
7: stop(res[[2]])
6: CRS(value)
5: ReplProj4string(obj, CRS(value))
4: `proj4string<-`(`*tmp*`, value = obj$crs)
3: `proj4string<-`(`*tmp*`, value = obj$crs)
2: .prepare_AEA_AOI(obj = aoi, res = res)
1: mukey.wcs(db = "gnatsgo", aoi = a)
```

In case it's relevant, my installed libproj is version 5.2.0-1

**Comment by brownag** [comment]
@potash The latest version of libproj is 7.2.1 -- are you staying on PROJ<6 for any particular reason? Most major distributions, and Windows binaries etc are on 6.3.1 at least. I suspect that there is some interaction with your relatively recent versions of sp/rgdal and your older version of libproj.

**Comment by brownag** [comment]
What is the output of `library(rgdal)` in a fresh session? This should print version numbers of all your geospatial binaries

**Comment by potash** [comment]
@brownag I am using proj from the Debian stable (buster) repository: https://packages.debian.org/buster/libproj-dev

I prefer not to manually install packages outside of the stable repository but i could try tomorrow or the next day. Here are the other versions:

```
> library(rgdal)
Loading required package: sp
rgdal: version: 1.5-18, (SVN revision 1082)
Geospatial Data Abstraction Library extensions to R successfully loaded
Loaded GDAL runtime: GDAL 2.4.0, released 2018/12/14
Path to GDAL shared files: /usr/share/gdal
GDAL binary built with GEOS: TRUE 
Loaded PROJ runtime: Rel. 5.2.0, September 15th, 2018, [PJ_VERSION: 520]
Path to PROJ shared files: (autodetected)
Linking to sp version:1.4-4
```

**Comment by brownag** [comment]
@potash Before you go and take all the time to build those from source... I took a look at this in a Buster VM. 

Replace: `crs = '+init=EPSG:4326'` with `crs = '+proj=longlat +datum=WGS84'` or `crs = '+init=epsg:4326'`

This worked for me on Debian 10 Buster with an completely "stable" build (R 3.5.2, too!). Pretty insidious because those CRS should be (are) equivalent... seems that it comes down to case sensitivity of "EPSG" v.s "epsg" when using the `+init` style on PROJ 5.2.0.

``` r
library(soilDB)
library(sp)
library(rgdal)
#> rgdal: version: 1.5-19, (SVN revision 1092)
#> Geospatial Data Abstraction Library extensions to R successfully loaded
#> Loaded GDAL runtime: GDAL 2.4.0, released 2018/12/14
#> Path to GDAL shared files: /usr/share/gdal
#> GDAL binary built with GEOS: TRUE 
#> Loaded PROJ runtime: Rel. 5.2.0, September 15th, 2018, [PJ_VERSION: 520]
#> Path to PROJ shared files: (autodetected)
#> Linking to sp version:1.4-4
library(raster)
library(rasterVis)
#> Loading required package: lattice
#> Loading required package: latticeExtra
#> Loading required package: RColorBrewer
library(viridis)
#> Loading required package: viridisLite


# AOI corners in WGS84 GCS
# xmin, ymin, xmax, ymax
a <- list(
  aoi = c(-114.16, 47.65, -114.08, 47.68),
  crs = '+init=epsg:4326'
)
x <- mukey.wcs(db = 'gnatsgo', aoi = a)

# OK
levelplot(x, att = 'ID', margin = FALSE, colorkey = FALSE, col.regions = viridis)
```

![](https://i.imgur.com/LF8FWIx.png)

**Comment by potash** [comment]
@brownag, weird! Works for me too. Thanks for figuring this out.

**Comment by potash** [comment]
@dylanbeaudette should I be able to query the value added (VALU1) table now? I tried the following:

```
> sql_valu <- sprintf("SELECT mukey, soc0_100 FROM valu1 WHERE mukey IN %s", IS)
> tab_valu <- SDA_query(sql_valu)
Warning message:

Invalid query: Invalid object name 'valu1'. 
```

I am brand new to SDA so this may be a silly question, thanks for your guidance!

**Comment by dylanbeaudette** [comment]
Glad that the suggestion by @brownag worked for you. It kind of makes sense, as the `proj4` style syntax used for {sp} arguments is case sensitive.

As for the latest: the `value1` table is not available in SDA. It may be in the near future. Working on options.

**Comment by potash** [comment]
That explains it. Looking forward to whatever you come up with.

**Comment by brownag** [comment]
I would say that this experimental interface is pretty well integrated at this point, so closing this issue. Any bugs or problems with these functions may be addressed in a new issue.
