### ISSUE TITLE
SDA_query without IO

### ISSUE THREAD

**Issue by bocinsky** [ncss-tech/soilDB#15]
Hi Dylan~
I'm in the process of using your excellent soilDB package for some point extractions from SSURGO, but needed a SDA_query-like function without writing to disk. I worked one out, and thought I would share as an issue (in lieu of a pull request). Note that it uses tibbles, as opposed to data.frames... it will work just as well with data.frames, though. Hope you are well!

Best,
Kyle

```{r}
SDA_query <- function (q) 
{
  if (!requireNamespace("httr", quietly = TRUE) |
      !requireNamespace("jsonlite", quietly = TRUE) |
      !requireNamespace("readr", quietly = TRUE)) 
    stop("please install the `httr`, `jsonlite`, and `readr` packages", 
         call. = FALSE)
  
  df <- httr::POST(url = "https://sdmdataaccess.sc.egov.usda.gov/tabular/post.rest", 
             body = list(query = q, format = "json+columnname") %>%
               jsonlite::toJSON(auto_unbox = TRUE)) %>%
    httr::stop_for_status() %>%
    httr::content(simplifyVector = T) %$%
    Table %>%
    tibble::as_tibble()

  colnames(df) <- df[1,]
  df <- df[-1,]
  
  df %<>%
    dplyr::mutate_all(.funs = funs(parse_guess))

  return(df)
  
}
```

**Comment by dylanbeaudette** [comment]
Excellent idea, thanks!

`SDA_query()` has been re-written since this issue was first opened.
