### ISSUE TITLE
lattice import / HenryTimeLine

### ISSUE THREAD

**Issue by brownag** [ncss-tech/soilDB#151]
We currently import {lattice} for only one method `panel.abline` in `HenryTimeLine`. The `panel.abline` method is used in several `misc/` scripts, too,  but we don't need the dependency. 

There is a TODO to move the Henry timeline method to {sharpshootR} -- where it fits the idea of "high level visualization" for that package.

There are a bunch of developments going on in this dynamic soil properties / moisture / time-series sphere -- and I know @dylanbeaudette is planning on revamping a lot of code to/in sharpshootR. 

So I am creating this issue to tag to make sure the `HenryTimeLine` functionality gets moved over -- as a benefit, we can then drop the lattice import in soilDB.

 - [x] Move `HenryTimeLine` to {sharpshootR}
 - [x] Remove `panel.abline` import
 - [ ] Verify that `misc/` demos still work

**Comment by dylanbeaudette** [comment]
No relevant demos in misc/ but there is a tutorial at http://ncss-tech.github.io/AQP/soilDB/Henry-demo.html which has been updated.
