### ISSUE TITLE
funky Rd -> roxygen conversion?

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/soilDB#164]
Yo @brownag whats going on here:
https://github.com/ncss-tech/soilDB/blob/5588248b527a5095425eddc7faf9e7760b52a64e/R/ROSETTA.R#L166

Is this an artifact of an out of sync branch, or .Rd files converted to roxygen when they really didn't need to be. If this is the case, then it would seem that all .Rds (?) were converted?

**Comment by brownag** [comment]
Nothing is out of sync. That looks like some funky formatting from the \doi{} tags that are required for those links.
All .Rds were converted.

**Comment by dylanbeaudette** [comment]
Check out the link above, there are two specifications (one mine 76-153, one automated 166-296?) of the documentation for `ROSETTA()`.

**Comment by brownag** [comment]
I looked at the link... the autogenerated one has a bunch of extra markup from the \doi tag. You can certainly delete the extra one, sorry about that.

**Comment by dylanbeaudette** [comment]
It would appear that all of the existing roxygen was replaced in this process, but not all have duplicate documentation.

No duplication here:
https://github.com/ncss-tech/soilDB/blob/nasisDBI/R/ISSR800.R
vs.
https://github.com/ncss-tech/soilDB/blob/master/R/ISSR800.R

Duplication here: https://github.com/ncss-tech/soilDB/blob/nasisDBI/R/KSSL_VG_model.R

A style note, but something I prefer when writing documentation in roxygen: why the omission of `@title, @description, @details` and hard-wrapped lines?  I can re-add, cleanup for human-readability, and delete the duplication, in this branch but will leave the issue open until it is done. Thankfully there won't be too many more of these.

**Comment by brownag** [comment]
So to be clear all of my changes were on the nasisDBI branch. 
I did not actively omit those, that is the default style.  And please do not change anything in the nasisDBI branch I will fix it, sorry, I was confused, I didn't merge this into master for good reason.

**Comment by dylanbeaudette** [comment]
Sounds good, thanks.

**Comment by brownag** [comment]
I will see if i can fix the hardwrapping and stuff to something a bit more pleasing, too
