### ISSUE TITLE
add check for same top and bottom horizon depths to fetchNASIS?

### ISSUE THREAD

**Issue by bakerjb** [ncss-tech/soilDB#17]
if top and bottom horizon depths have the same value, it creates an error in functions that subtract one from the other (divide by 0)
for example the aggregateColor function uses hxdepb-hzdept

**Comment by dylanbeaudette** [comment]
Great idea. How about this: if the `top == bottom` then `bottom <- top + 1` ? That would be a simple "fix" for `fetchNASIS()`. Better ideas?

**Comment by smroecker** [comment]
Good idea.

**Comment by dylanbeaudette** [comment]
Andrew Brown suggested checking to ensure that editing the bottom depth should only happen after ensuring that the affected horizon is at the "bottom" of the profile.

**Comment by dylanbeaudette** [comment]
After some testing (1000+ pedons from MLRA 18 and 22A) that included 306 horizons with `top == bottom`, seems that adding 1 cm to the bottom works well and there are no overlaps created.

Fixed in 195c67f876e66ef8a16e5dda442aba162e30a3d9
