### ISSUE TITLE
musym sometimes erroneously converted to numeric

### ISSUE THREAD

**Issue by kevinwolz** [ncss-tech/soilDB#190]
Here is a simple call to `get_mapunit_from_SDA()` with random mysym values:
`out.multiple <- soilDB::get_mapunit_from_SDA(WHERE = "musym IN ('8E2', '671A')")`

The call results in a data frame with musyms as expected:
```
unique(out.multiple$musym)
[1] "671A" "8E2"
```

However, if we make this same call with just the first musym, returned musym values in the resulting data frame are not correct:
```
out.single <- soilDB::get_mapunit_from_SDA(WHERE = "musym IN ('8E2')")
unique(out.single$musym)
[1] "800"
```

It seems that some point in the process "8E2" is getting erroneously interpreted as scientific notation and converted to numeric. This must not happen when both musyms in the first example are run together because "671A" can not be interpreted as numeric in any standard way, and so the whole musym column remains as character. 

After doing some digging, it looks like this erroneous conversion is done by `utils::type.convert()`, which is called by `.post_process_SDA_result_set()`, which in turn is called as part of the data cleaning process  in `SDA_query()`. 

I don't have a great alternative to propose off hand. It would probably be worth checking to see if any other variables might experience an erroneous conversion like this and select a solution that works across the board. 

How unfortunate that some musyms can be interpreted as scientific notation! I admit that this is likely a very rare case that you supply only these tricky musyms in a query, but, at the same time, musyms that end in "E2" or "E3" are actually quite common.

**Comment by dylanbeaudette** [comment]
That is a tough one. I'm having a hard time finding an alternative to `type.convert()`. Looks like `read.csv()` will do the same thing when there is a column contains a single value that looks like scientific notation.

News to me!
```r
read.csv(textConnection('musym\n"8E2"'))

#   musym
# 1   800
```

Two ideas:
  * keep track of which column contains `musym`, make a copy before `type.convert()` and then replace results if the column classes changes from `character` to `numeric` (feels like a hack)
  * Work with the SDA devs on a new JSON format that *doesn't* quote every column as if it were character (this will take time)

**Comment by brownag** [comment]
@kevinwolz  your example demonstrates the problem well. I am not sure what your use case is but clearly we want to be able to return accurate musym regardless of how specific a query is or how you encountered this problem. I would say @dylanbeaudette's 2nd idea is the way to go here in the long run; so we can be explicit about "expected" data types in JSON result rather than needing to call `type.convert()` . But otherwise this is (unfortunate) base R behavior.

A third idea / workaround for one-off queries could be to use SQL `CONCAT()` to add something for sensitive columns to avoid the numeric conversion and processing after to remove it. 

``` r
soilDB::SDA_query("select distinct areasymbol, mukey, nationalmusym, muname, concat(':',musym) as musym from mapunit inner join legend on mapunit.lkey = legend.lkey where musym in ('8E2')")
#> single result set, returning a data.frame
#>    areasymbol   mukey nationalmusym
#> 1       IL009  173003         2w1yv
#> 2       IL057  615618         2w1yv
#> 3       IL065  175148         2w1yt
#> 4       IL185  179713         2w1yv
#> 5       IL047  175492         2w1yt
#> 6       IL149  201087         2w1yv
#> 7       IL171 2542046         2w1yv
#> 8       IL137 1672181         2w1yv
#> 9       IL159 2026808         2w1yt
#> 10      IL001 2378571         2w1yv
#>                                                muname musym
#> 1  Hickory silt loam, 18 to 25 percent slopes, eroded  :8E2
#> 2  Hickory silt loam, 18 to 25 percent slopes, eroded  :8E2
#> 3  Hickory silt loam, 10 to 18 percent slopes, eroded  :8E2
#> 4  Hickory silt loam, 18 to 25 percent slopes, eroded  :8E2
#> 5  Hickory silt loam, 10 to 18 percent slopes, eroded  :8E2
#> 6  Hickory silt loam, 18 to 25 percent slopes, eroded  :8E2
#> 7  Hickory silt loam, 18 to 25 percent slopes, eroded  :8E2
#> 8  Hickory silt loam, 18 to 25 percent slopes, eroded  :8E2
#> 9  Hickory silt loam, 10 to 18 percent slopes, eroded  :8E2
#> 10 Hickory silt loam, 18 to 25 percent slopes, eroded  :8E2
```

---

As an aside I would be a bit cautious when using musym in WHERE unless there are additional constraints on soil survey area. Consider refactoring workflows that may have you querying single musyms like this. Note that in example there are two slope phases of Hickory silt loam with two national map units and 10 distinct soil survey area legends--all of which have musym "8E2". A good example of how it can be risky to assume same musym refers to the same "thing" in different areas. 

mukey and nationalmusym are more "reliable" as unique map unit identifiers; combined they uniquely identify shared concepts across political boundaries. mukey is always numeric and nationalmusym is always* character and they should not suffer from this conversion problem because of how they are generated; whereas musym is free-form essentially and varies a lot with region and vintage.

**Comment by dylanbeaudette** [comment]
I'm hesitant to add any hacks to `SDA_query` at this time, unless they are activated by an additional argument. Also, the incorrect interpretation of the source data (JSON arrays of character data) is more of a base R issue.

I was curious about how / why this might be happening and why I haven't seen it before with similar data processed via `jsonLite`.

Here is the "compact" JSON returned by SDA.
```json
{"Table":[["areasymbol","mukey","nationalmusym","muname","musym"],["IL009","173003","2w1yv","Hickory silt loam, 18 to 25 percent slopes, eroded","8E2"],["IL057","615618","2w1yv","Hickory silt loam, 18 to 25 percent slopes, eroded","8E2"],["IL065","175148","2w1yt","Hickory silt loam, 10 to 18 percent slopes, eroded","8E2"],["IL185","179713","2w1yv","Hickory silt loam, 18 to 25 percent slopes, eroded","8E2"],["IL047","175492","2w1yt","Hickory silt loam, 10 to 18 percent slopes, eroded","8E2"],["IL149","201087","2w1yv","Hickory silt loam, 18 to 25 percent slopes, eroded","8E2"],["IL171","2542046","2w1yv","Hickory silt loam, 18 to 25 percent slopes, eroded","8E2"],["IL137","1672181","2w1yv","Hickory silt loam, 18 to 25 percent slopes, eroded","8E2"],["IL159","2026808","2w1yt","Hickory silt loam, 10 to 18 percent slopes, eroded","8E2"],["IL001","2378571","2w1yv","Hickory silt loam, 18 to 25 percent slopes, eroded","8E2"]]}
```

Here the the more expressive, but less efficient output from `jsonLite::toJSON`.
```json
[{"areasymbol":"IL009","mukey":173003,"nationalmusym":"2w1yv","muname":"Hickory silt loam, 18 to 25 percent slopes, eroded","musym":"8E2"},{"areasymbol":"IL057","mukey":615618,"nationalmusym":"2w1yv","muname":"Hickory silt loam, 18 to 25 percent slopes, eroded","musym":"8E2"},{"areasymbol":"IL065","mukey":175148,"nationalmusym":"2w1yt","muname":"Hickory silt loam, 10 to 18 percent slopes, eroded","musym":"8E2"},{"areasymbol":"IL185","mukey":179713,"nationalmusym":"2w1yv","muname":"Hickory silt loam, 18 to 25 percent slopes, eroded","musym":"8E2"},{"areasymbol":"IL047","mukey":175492,"nationalmusym":"2w1yt","muname":"Hickory silt loam, 10 to 18 percent slopes, eroded","musym":"8E2"},{"areasymbol":"IL149","mukey":201087,"nationalmusym":"2w1yv","muname":"Hickory silt loam, 18 to 25 percent slopes, eroded","musym":"8E2"},{"areasymbol":"IL171","mukey":2542046,"nationalmusym":"2w1yv","muname":"Hickory silt loam, 18 to 25 percent slopes, eroded","musym":"8E2"},{"areasymbol":"IL137","mukey":1672181,"nationalmusym":"2w1yv","muname":"Hickory silt loam, 18 to 25 percent slopes, eroded","musym":"8E2"},{"areasymbol":"IL159","mukey":2026808,"nationalmusym":"2w1yt","muname":"Hickory silt loam, 10 to 18 percent slopes, eroded","musym":"8E2"},{"areasymbol":"IL001","mukey":2378571,"nationalmusym":"2w1yv","muname":"Hickory silt loam, 18 to 25 percent slopes, eroded","musym":"8E2"}]
```

The `musym` field in the latter JSON is correctly interpreted as character data. I don't think that it is wise to have SDA return this more expressive form of JSON until we have some kind of on-the-fly compression system worked out. In the meantime, it shouldn't be all that hard to have an additional SDA output driver (the current driver is `JSON+COLUMNNAME`) that includes and additional row of data types.

**Comment by dylanbeaudette** [comment]
Please test #191 and report back on any unexpected results.

**Comment by dylanbeaudette** [comment]
Thanks @kevinwolz and @brownag for reporting and contributing to a quick solution. `SDA_query()` should be a heck of a lot more robust now.
