### ISSUE TITLE
get_SDA_property() incorrect aggregation with "Weighted Average"

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/soilDB#193]
Back to a common thread: what is the "official" (or reasonable in the absence of a standard) approach to a weighted-average style aggregation when dealing with a mixture of soil + non-soil components that all have records in the `chorizon` table?

Except for cases in which a "stock" is being computed, I've always removed weights associated with the NA values from the calculation. It appears that WSS is also doing this.

``` r
library(soilDB)

# an example map unit + components
SDA_query("SELECT mukey, component.cokey, compname, compkind, comppct_r, hzdept_r, hzdepb_r, sandtotal_r FROM component INNER JOIN chorizon ON component.cokey = chorizon.cokey WHERE mukey = '545857' ORDER BY comppct_r DESC, hzdept_r ASC;")
#> single result set, returning a data.frame
#>    mukey    cokey     compname           compkind comppct_r hzdept_r hzdepb_r
#> 1 545857 20066590 Rock outcrop Miscellaneous area        60        0      203
#> 2 545857 20066591    Cleveland             Series        30        0       13
#> 3 545857 20066591    Cleveland             Series        30       13       36
#> 4 545857 20066591    Cleveland             Series        30       36      203
#>   sandtotal_r
#> 1          NA
#> 2        67.4
#> 3        67.4
#> 4          NA

# matches WSS: NA / NULL returned because the largest component has no data
get_SDA_property(property = c("sandtotal_r","silttotal_r","claytotal_r"),
                 method = "Dominant Component (Numeric)", 
                 mukeys = 545857,
                 top_depth = 0,
                 bottom_depth = 25)
#>   areasymbol musym                                                  muname
#> 1      NC113   RkF Rock outcrop-Cleveland complex, 30 to 95 percent slopes
#>    mukey sandtotal_r silttotal_r claytotal_r
#> 1 545857          NA          NA          NA

# does not match WSS
# (sand should be 67.4%, silt should be 19.6%, clay should be 13%)
get_SDA_property(property = c("sandtotal_r","silttotal_r","claytotal_r"),
                       method = "Weighted Average", 
                       mukeys = 545857,
                       top_depth = 0,
                       bottom_depth = 25)
#>   areasymbol musym                                                  muname
#> 1      NC113   RkF Rock outcrop-Cleveland complex, 30 to 95 percent slopes
#>    mukey sandtotal_r silttotal_r claytotal_r
#> 1 545857       22.24        6.47        4.29

# check source data
get_SDA_property(property = c("sandtotal_r","silttotal_r","claytotal_r"),
                 method = "None", 
                 mukeys = 545857,
                 top_depth = 0,
                 bottom_depth = 25)
#>   areasymbol musym                                                  muname
#> 1      NC113   RkF Rock outcrop-Cleveland complex, 30 to 95 percent slopes
#> 2      NC113   RkF Rock outcrop-Cleveland complex, 30 to 95 percent slopes
#> 3      NC113   RkF Rock outcrop-Cleveland complex, 30 to 95 percent slopes
#> 4      NC113   RkF Rock outcrop-Cleveland complex, 30 to 95 percent slopes
#>    mukey    cokey    chkey     compname comppct_r hzdept_r hzdepb_r sandtotal_r
#> 1 545857 20066590 58863333 Rock outcrop        60        0      203          NA
#> 2 545857 20066591 58863335    Cleveland        30        0       13        67.4
#> 3 545857 20066591 58863336    Cleveland        30       13       36        67.4
#> 4 545857 20066591 58863334    Cleveland        30       36      203          NA
#>   silttotal_r claytotal_r
#> 1          NA          NA
#> 2        19.6          13
#> 3        19.6          13
#> 4          NA          NA


# incorrect values are re-created when manually performing the wt. avg
# that includes all of the weights
sum(c(60, 30) * c(NA, 67.4), na.rm = TRUE) / sum(c(60, 30))
#> [1] 22.46667
sum(c(60, 30) * c(NA, 19.6), na.rm = TRUE) / sum(c(60, 30))
#> [1] 6.533333
sum(c(60, 30) * c(NA, 13), na.rm = TRUE) / sum(c(60, 30))
#> [1] 4.333333
```

For reference, here is the output for `sandtotal_r` 0-25cm wt. average from WSS:
![image](https://user-images.githubusercontent.com/624277/124185736-34164880-da70-11eb-99b4-18fd8099b247.png)

Adding @cferguso and @jneme910

**Comment by brownag** [comment]
Thanks for bringing this back up. I made a pull request (#194) with a proposed fix for this that allows toggling via `miscellaneous_areas` with a default (FALSE) that has parity with the WSS result.

**Comment by brownag** [comment]
I personally think that populating horizon records for a miscellaneous areas is an "error"-- but there are nearly 25,000 components in SSURGO/STATSGO component table that are miscellaneous areas with horizon data populated. Apparently some of them even have multiple horizons!

``` r
soilDB::SDA_query("SELECT COUNT(DISTINCT mukey) AS n_bad_mapunit, 
                          COUNT(DISTINCT component.cokey) AS n_bad_component, 
                          COUNT(DISTINCT chkey) AS n_bad_chorizon FROM component 
                   INNER JOIN chorizon ON component.cokey = chorizon.cokey 
                   WHERE compkind = 'Miscellaneous area'")
#> single result set, returning a data.frame
#>   n_bad_mapunit n_bad_component n_bad_chorizon
#> 1         23120           24994          29493
```

**Comment by dylanbeaudette** [comment]
I've heard people talking about creating fake horizon records with only horizon depths and designation. Until this is rectified (I'll bring it up with SBS staff) we have to work around it. I didn't realize that you could use DISTINCT like that, cool.

I've thought of another case, besides misc. areas + hz data: missing values in "normal" components. It isn't always clear how one should interpret a component that is missing a single horizon worth of data when aggregating over some depth interval, but it happens. For example, some properties associated with duripans in the San Joaquin, Redding, and related series (mostly in older surveys) are missing.

The use of thickness-weights in the presence of missing properties will suffer from the same "dilution" effect. Consider:

``` r
library(aqp)
#> This is aqp 1.30
#> 
#> Attaching package: 'aqp'
#> The following object is masked from 'package:stats':
#> 
#>     filter
library(soilDB)

# missing sand in the Btqm (H3)
x <- fetchSDA(WHERE = "mukey = '461957'", duplicates = TRUE)
#> single result set, returning a data.frame
#> single result set, returning a data.frame
#> single result set, returning a data.frame
#> empty result set
#> single result set, returning a data.frame
#> single result set, returning a data.frame
#> empty result set
#> single result set, returning a data.frame
#> converting profile IDs from integer to character
#> converting horizon IDs in column `chkey` to character
# plotSPC(x, color = 'sandtotal_r')

# source data
get_SDA_property(property = 'sandtotal_r', method = 'None', mukeys = 461957, top_depth = 0, bottom_depth = 100)
#> single result set, returning a data.frame
#>   areasymbol musym                                                muname  mukey
#> 1      CA067   213 San Joaquin silt loam, leveled, 0 to 1 percent slopes 461957
#> 2      CA067   213 San Joaquin silt loam, leveled, 0 to 1 percent slopes 461957
#> 3      CA067   213 San Joaquin silt loam, leveled, 0 to 1 percent slopes 461957
#> 4      CA067   213 San Joaquin silt loam, leveled, 0 to 1 percent slopes 461957
#>      cokey    chkey    compname comppct_r hzdept_r hzdepb_r sandtotal_r
#> 1 19800184 57892903 San Joaquin        85        0       58        26.5
#> 2 19800184 57892901 San Joaquin        85       58       71        27.6
#> 3 19800184 57892900 San Joaquin        85       71      137          NA
#> 4 19800184 57892902 San Joaquin        85      137      152        43.0

# clearly not correct
get_SDA_property(property = 'sandtotal_r', method = 'Weighted Average', mukeys = 461957, top_depth = 0, bottom_depth = 100)
#> single result set, returning a data.frame
#>   areasymbol musym                                                muname  mukey
#> 1      CA067   213 San Joaquin silt loam, leveled, 0 to 1 percent slopes 461957
#>   sandtotal_r
#> 1       18.96

# this correct within the data we have
# interpretation is up for discussion
slab(x, fm = ~ sandtotal_r, slab.structure = c(0, 100), slab.fun = mean, na.rm = TRUE)
#>      variable all.profiles    value top bottom contributing_fraction
#> 1 sandtotal_r            1 26.70141   0    100                  0.71
```

I'd advocate for a more generic solution that involves removing weights associated with missing values. This is much harder to do within the current SQL (based on my quick look). Clever solutions welcome.

**Comment by brownag** [comment]
I generally agree that a more generic solution is the way to go in long run... but consider that in existing SQL query there are several in-lieu texture modifiers filtered out to handle these types of soil profiles with "allowed" absence of data

```sql
AND texture NOT LIKE '%%PM%%' AND texture NOT LIKE '%%DOM' AND texture NOT LIKE '%%MPT%%' AND texture NOT LIKE '%%MUCK' AND texture NOT LIKE '%%PEAT%%' AND texture NOT LIKE '%%br%%' AND texture NOT LIKE '%%wb%%' 
```

There appears to be at least two two pedogenically-important ones missing from the set: `"CEM"`, and `"IND"`. That San Joaquin component Btqm horizon in your example uses `"IND"` as its texture and I believe `CEM-something` has been used in more recent components which might be worth some discussion as well. 

I propose in the interim we could add (try it in #194)
 
```sql 
AND texdesc NOT LIKE '%%indurated%%' AND texture NOT LIKE '%%cem%%'
```

Adding that constraint in  `get_SDA_property()` works as expected for your example and some other duripans I knew of in CA077.

```r
soilDB::get_SDA_property(property = 'sandtotal_r', method = 'Weighted Average', mukeys = 461957, top_depth = 0, bottom_depth = 100)
#>   areasymbol musym                                                muname  mukey
#> 1      CA067   213 San Joaquin silt loam, leveled, 0 to 1 percent slopes 461957
#>   sandtotal_r
#> 1        26.7
```

As a "counter-argument" to filtering out whole horizons based on in lieu texture... there are quite a few horizons out there that DO have sand populated and have cemented or indurated modifier. Note also using  `texdesc` helps to filter out "IND" without getting "CIND" (cinders)... so this style of filtering with SQL LIKE has limitations.

---

I was curious what was populated for texture groups for horizons where `sandtotal_r` (for instance) was NULL. There are a few in there I am not very familiar with that also might be worth filtering. 

The texture groups that are not obsolete and refer to pedogenically cemented or otherwise coherent materials are I believe "legitimate" reasons to have sand values not populated and therefore removed from aggregation. 

If it is only weakly or extremely weakly cemented though; or stratified cemented-noncemented materials... I could perhaps see the value in using whatever values were populated (if any, and if value missing drop the weights for that layer) since the values in those cases were likely chosen considering their interpretive value.

``` r
# get texturegrp for horizons where sand is null
res <- soilDB::SDA_query("SELECT texture FROM chorizon 
                          INNER JOIN chtexturegrp ON chtexturegrp.chkey = chorizon.chkey
                          WHERE sandtotal_r IS NULL 
                          AND (texdesc LIKE '%indurated%'
                          OR texdesc LIKE '%cemented%')")
#> single result set, returning a data.frame
res2 <- trimws(unlist(strsplit(res$texture, split = "[- ]")))
sort(table(res2[nchar(res2) > 0]))
#> 
#>     C   DUR    LS  LVFS   STV   BYX   COS  COSL  LCOS  PGRX    WB   CBX  ASHY 
#>     1     1     1     1     1     2     2     2     2     2     2     3     4 
#>    CB   GYP  SICL  VFSL    SG  MEDL     S    GR   GRX   SIL    SL   GRV    BR 
#>     4     4     4     4     7     8    16    17    29    58    74    93   151 
#>    SR   IND   MAT   CEM 
#>   155  3896  9217 11742

# compare to those that do have sand populated
res3 <- soilDB::SDA_query("SELECT texture FROM chorizon 
                           INNER JOIN chtexturegrp ON chtexturegrp.chkey = chorizon.chkey
                           WHERE sandtotal_r IS NOT NULL 
                           AND (texdesc LIKE '%indurated%'
                           OR texdesc LIKE '%cemented%')")
#> single result set, returning a data.frame
res4 <- trimws(unlist(strsplit(res3$texture, split = "[- ]")))
sort(table(res4[nchar(res4) > 0]))
#> 
#>    C   FS  GRF   CL LVFS    G PGRV  DUR  BYX  STV  STX SICL VFSL MEDL  LFS  IND 
#>    1    1    1    2    3    4    4    5    6    6    6    9   10   13   17   19 
#>  CBV  COS   SR  FSL   CB  SCL  CBX ASHY    L LCOS COSL    S  SIL   LS  GRX  GRV 
#>   23   23   34   36   38   42   44   54   54   55   56   84   90  126  130  169 
#>   GR   SL  MAT  CEM 
#>  229  279  357 1252
```

**Comment by brownag** [comment]
I neglected the fact that Ksat is populated for duripans and other cemented horizons and should be included for WSS parity in weighted average. For your San Joaquin component the expected weighted average 0-100cm `ksat_r` is 5.2494. Filtering out the indurated horizon as I did above gives a value of 7.39... 

```r
get_SDA_property(property = c("ksat_r"),
                 method = "Weighted Average", 
                 mukeys = 461957,
                 top_depth = 0,
                 bottom_depth = 100)
```

I reverted the addition of indurated and cemented to the query. https://github.com/ncss-tech/soilDB/pull/194/commits/caeb32738ab01df88153eaf75bcc433cdbb46127

**Comment by dylanbeaudette** [comment]
It was a good idea: in a perfect database we could filter on criteria related to the presence/absence of certain properties. Given the state of the database and possible "reasons" for missing values, an NA filter is the most generic solution.

I'll try and restate the problem as it occurs at two distinct "levels":
  * filtering entire components based on `chorizon` records that are missing data (dilution `comppct_r`)
  * filtering horizons based on single fields with NULL values (dilution of thickness-weight)

Again, doing all of this in SQL and maintaining alignment with SOD is a challenge. For a single property this is simple: just add an additional constraint to the WHERE clause. For multiple properties in the same query, I've use a CASE WHEN statement to conditionally set thickness weights to 0. Those horizon depth CASE WHEN statements are already pretty complex...

Here is a snippet from the ISSR-800 and related SQL:
```sql
sandtotal_r as sand, CASE WHEN sandtotal_r is NULL THEN NULL ELSE (hzdepb_r - hzdept_r) END as sand_wt,
silttotal_r as silt, CASE WHEN silttotal_r is NULL THEN NULL ELSE (hzdepb_r - hzdept_r) END as silt_wt,
claytotal_r as clay, CASE WHEN claytotal_r is NULL THEN NULL ELSE (hzdepb_r - hzdept_r) END as clay_wt,
```

**Comment by brownag** [comment]
What's a few nested `CASE WHEN` statements among friends? /s

It's not too difficult to add custom weights with NULL values dropped for each property requested in the SOD style query. I think I realized this would be a problem when I vectorized it but perhaps did not drill down into these cases sufficiently and was not trying to change the handling of NULL etc from the original SOD queries where possible.

See #194 https://github.com/ncss-tech/soilDB/pull/194/commits/5cd136121686cfbd10efedfb8630d7de1e3cef3ewhich now gives the following multi-property weighted average result when some values are NULL.

``` r
soilDB::get_SDA_property(property = c("sandtotal_r","ksat_r"),
method = "Weighted Average",
mukeys = 461957,
top_depth = 0,
bottom_depth = 100)
#>   areasymbol musym                                                muname  mukey
#> 1      CA067   213 San Joaquin silt loam, leveled, 0 to 1 percent slopes 461957
#>   sandtotal_r ksat_r
#> 1        26.7   5.25
```

This result reminds me of the `CAST(foo AS decimal(5,2))` used in all of these queries -- it seems that WSS is not as heavy-handed about rounding.
