### ISSUE TITLE
automatic conversion of `texture_class` to factor

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/soilDB#2]
It would be useful to set the factor levels according to a logical sequence.

**Comment by pierreroudier** [comment]
Could you post a (mockup) use case?

Gut feeling is that it could be pretty difficult to implement given the "intelligence" required to support different texture description systems.

One way to address this could be to:
- Leave to the user to order the levels of their texture data in the `SoilProfileCollection` *before* plotting
- We could facilitate this using a dedicated function

Eg:

```
spc <- order_texture(spc$texture, ...)
plot(spc)
```

**Comment by dylanbeaudette** [comment]
Good point. This would initially be used by the (NRCS-centric) set of functions: `fetchNASIS`, etc. You are correct, there are too many possible classes and several ways of organizing them into a 1D ordering.

I like the idea of a more generic approach--should probably be a function in the aqp package, with options to support multiple sorting schemes.
