### ISSUE TITLE
volume % fragments, excluding parafrags

### ISSUE THREAD

**Issue by brownag** [ncss-tech/soilDB#20]
On branch 'Parafractions' (commit 6e576a4) simplifyFragmentData() outputs a dataframe with an additional column `total_frags_pct_nopf`. This is calculated in the same way as `total_frags_pct` except it omits the columns containing the "para"-fractions from the row sum calculation on the phfrags-derived dataframe.

Therefore, functions relying on fetchNASIS() or other functions that use simplifyFragmentData() will now have another variable available reflecting the parafragment-free totals.

**Comment by dylanbeaudette** [comment]
ok to close this?

**Comment by brownag** [comment]
Parafractions was merged into master branch; issue closed
