### ISSUE TITLE
switch WCS interfaces to EPSG:5070

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/soilDB#205]
Recent conversations 

Changes in:

- [x] `ISSR800` WCS
- [x] `mukey` WCS
- [x] `seriesExtent`
- [x] `taxaExtent`
- [x] WCS server configuration
- [x] documentation
- [x] tutorials
- [x] S4SS materials I and II

**Comment by brownag** [comment]
Unchecked `seriesExtent()` and `taxaExtent()` from this list because they do not return a EPSG:5070 CRS. There is a small discrepancy in the ellipsoid that should be corrected in the source grids.

Current series/taxaExtent grid CRS
```
PROJCRS["unnamed",
    BASEGEOGCRS["NAD83",
        DATUM["North American Datum 1983",
            ELLIPSOID["GRS 1980",6378137,298.257222101004,
                LENGTHUNIT["metre",1]]],
...
```

Expected CRS (EPSG:5070)
```
PROJCRS["NAD83 / Conus Albers",
    BASEGEOGCRS["NAD83",
        DATUM["North American Datum 1983",
            ELLIPSOID["GRS 1980",6378137,298.257222101,
                LENGTHUNIT["metre",1]]],
...
```

**Comment by dylanbeaudette** [comment]
Re-making the taxa + series grids now, with EPSG:5070 as the CRS. Should result in the exact  / expected embedded CRS information.

**Comment by dylanbeaudette** [comment]
Tested taxa extent and series extent grids, both return an exact specification for 5070.
