### ISSUE TITLE
ODBC won't read

### ISSUE THREAD

**Issue by MichaelSullivan2** [ncss-tech/soilDB#207]
![image](https://user-images.githubusercontent.com/76757413/132697109-d7020051-7a7e-44d7-9eb1-02e00f30a2a4.png)

I have a working ODBC connection but the fetch pedons command in R is still giving connection issues.

![image](https://user-images.githubusercontent.com/76757413/132697336-a6cd8168-5c8c-40df-99d1-232cf4f4b450.png)

I have Pedons and Sites table loaded into my selected set so that isn't the issue.

**Comment by brownag** [comment]
Do you have a more recent ODBC driver available in your ODBC Data Source Administrator? Such as ODBC Driver 13 for SQL Server”? Or is the "Native Client Version 11" the latest you have available? I have tested with both 13 and 11 and have not had this issue, but we might be having some driver differences. 

![image](https://user-images.githubusercontent.com/20842828/132701535-fde17959-f3b5-48a3-8b0d-8fed0e95fe70.png)

**Comment by dylanbeaudette** [comment]
How about the output from `sessionInfo()` after loading `soilDB`?

**Comment by brownag** [comment]
@dylanbeaudette good call. I worked with @MichaelSullivan2 and an update of soilDB to latest CRAN version did the trick.
