### ISSUE TITLE
`sieveCoarseFraction`

### ISSUE THREAD

**Issue by brownag** [ncss-tech/soilDB#217]
New function to consolidate `simplifyFragmentData` / `simplifyArtifactData` into a single routine #135 

Things that might be supported:
 - custom input column names (table specific) (mostly already addressed in `simplifyFragmentData`)
 - alternate sieve sizes (other non-USDA systems?)
 - custom output column names (beyond just prefixes)
 - custom functional summaries and naming
 - custom messages

**Comment by brownag** [comment]
Related #216, #46

**Comment by dylanbeaudette** [comment]
Note to self to make changes to `.sieve` and `.rockFragmentSieve` in order to generalize to non-USDA systems.

**Comment by brownag** [comment]
Made some progress towards this https://github.com/ncss-tech/soilDB/commit/c2f916bb5aff3a81072e5f9dc2edc1b9171d0918

I suggest the lowest-level `sieve()` function be exported from aqp. We can keep this internal `.sieve()` until we've got it into the package and on CRAN. The `sieves` argument is exposed to the user in soilDB at simplifyFragment/ArtifactData()

**Comment by brownag** [comment]
I think the main features that were identified in OP have been resolved, and a new`sieve()` function has been added to a PR (https://github.com/ncss-tech/aqp/pull/283) for inclusion in aqp 2.0.
