### ISSUE TITLE
Van Genuchten parameters in ROSETTA function

### ISSUE THREAD

**Issue by floveil** [ncss-tech/soilDB#226]
Hi,

I am using the R package _soilDB_ and in particular the function **ROSETTA()** for the calculation of Van Genuchten parameters. However, it is difficult to understand the output of the function and in particular the units of each output variable. 

It seems that the _alpha_ parameter given by the function is the same _alpha_ as the one in the Van Genuchten equation. In the package reference manual, _alpha_ is defined as log10(_alpha_) and is expressed in cm. 

Concerning the parameter called _npar_, does it correspond to the parameter _n_ in the Van Genuchten equation? In the reference manual of the package, the only information on this parameter is: npar: index of pore size distribution, function expects log10-transformed values with units of 1/cm. However, the parameter n in the equation is unitless.

Can you tell us if I understand the _alpha_ parameter given by the function, and then tell me if _npar_ corresponds to the n parameter of the Van Genuchten equation ? 

Thank you in advance.

**Comment by brownag** [comment]
Hello, 

Thanks for reaching out to help us improve our documentation.
`npar` does correspond to the parameter `n` in the Van Genuchten equation. 

The `ROSETTA()` function provides access to the USDA-ARS  USSL ROSETTA model API which is running the official https://github.com/usda-ars-ussl/rosetta-soil Python module. From the README of the rosetta-soil module I find this table: 

> The Rosetta pedotransfer function predicts five parameters for the van Genuchten model of unsaturated soil hydraulic properties
> 
> - theta_r : residual volumetric water content
> - theta_s : saturated volumetric water content
> - log10(alpha) : retention shape parameter [log10(1/cm)]
> - log10(n) : retention shape parameter
> - log10(ksat) : saturated hydraulic conductivity [log10(cm/d)]

I do see the reference to the `npar` argument equivalently further down the page where it is also referred to as a dimensionless shape parameter.

As far as the documentation for the `KSSL_VG_model()` function where you found the units for alpha and n--those appear to be wrong. I believe the dimensions of alpha are log10(1/cm) and log10(n) is dimensionless. To use these in the standard van Genuchten equation need to take inverse log first. This is what is done internally within the KSSL_VG_model() function to calculate the curve, before using the following equation:

`theta_r + ((theta_s - theta_r) / ((1 + (alpha * phi) ^ n ) ^ (1 - 1 / n)))`
