### ISSUE TITLE
NASIS data model update

### ISSUE THREAD

**Issue by smroecker** [ncss-tech/soilDB#238]
It appears the NASIS data model update broke fetchNASIS(from = "pedons"). Other soilDB functions are probably broken also. So we need to catalog and fix.

**Comment by brownag** [comment]
I have a routine in place to test all the NASIS functionality, so shouldn't be too hard to make a list of what's breaking. I am initializing my new local database now, will report back soon.

**Comment by brownag** [comment]
It appears that the only changes affecting existing NASIS queries were the removal of obsolete columns. 

There have been quite a few new child tables (e.g. Component Ecological Site History) that are of immediate interest for inclusion, but the minimal changes to get existing functions working with new data model are complete.

https://github.com/ncss-tech/soilDB/commit/4695359691fd06b29a977bfcb4233f690e365902
 - `fetchNASIS("pedons")` no longer includes `pmweathering`
 - `fetchNASIS("components")` no longer includes `ecositeorigin`
