### ISSUE TITLE
parseWebReport() usage

### ISSUE THREAD

**Issue by potash** [ncss-tech/soilDB#248]
Any tips on using parseWebReport()? Here is what I tried:

```R
url = "https://nasis.sc.egov.usda.gov/NasisReportsWebSite/limsreport.aspx?report_name=Pedon_Site_Description_usepedonid&pedon_id=1959IL063001"
> parseWebReport(url, list())
Error: Table has inconsistent number of columns. Do you want fill = TRUE?
> parseWebReport(url, list(), fill=TRUE)
Error in parseWebReport(url, list(), fill = TRUE) : 
  unused argument (fill = TRUE)
```

**Comment by dylanbeaudette** [comment]
Yeah, that is "expected" but also disappointing.  `parseWebReport()` was designed to work with tabular report output, and mostly for internal use. Lets talk directly about getting the source data in its original format: there is no simple interface to all of the pedon data (yet).

**Comment by potash** [comment]
Thanks for the example @brownag
