### ISSUE TITLE
write functions for getting / processing NASIS text notes

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/soilDB#25]

**Comment by brownag** [comment]
Do the following adequately cover the needs of this issue? 

- `get_cotext_from_NASIS_db()` (component)
- `get_mutext_from_NASIS_db()` (mapunit)
-  `get_text_notes_from_NASIS_db()` (pedon, site, siteobs, horizon, photo links)

Could we make this approach more generic allowing selecting text note results by table name or column name or data type?

**Comment by dylanbeaudette** [comment]
Seems fine.
