### ISSUE TITLE
Data loss when using uncode()

### ISSUE THREAD

**Issue by monikashea** [ncss-tech/soilDB#253]
I recently updated soilDB from 2.6.14 to 2.7.2. Since then I have had an issue with the cosoilmoist table, and I think I was able to track the issue down to the `uncode()` function. 

Bear with me: I am trying to access the cosoilmoist table so that I can get water table depth low, representative, and high values. In the past I was able to isolate this by filtering the rows where status == "Wet" and selecting dept_l, dept_r, and dept_h.

For the sake of this example:
`where <- "mukey IN ('426539', '426540', '426541')"` 

When I use `soilDB::get_cosoilmoist_from_SDA(WHERE = where)` there is no data in the "status" column (and also the "month" column is empty). I've looked at this in a few different counties throughout WI and IL and it's always the case, so it's not an issue with inconsistent data collection.

Before I knew this function was available in soilDB I made my own query and ran it through `SDA_query()`. Here is my query:
`q.cosoilmoist <- paste0("SELECT
    co.mukey, co.cokey, co.comppct_r, com.*, cosm.*
    FROM component AS co
    LEFT JOIN comonth AS com ON com.cokey = co.cokey
    LEFT JOIN cosoilmoist AS cosm ON cosm.comonthkey = com.comonthkey
    WHERE ", where, " ORDER BY co.mukey;")
`

After running `d.cosoilmoist <- soilDB::SDA_query(q.cosoilmoist)`, the month and soimoiststat  values are in the table! But after running `d.cosoilmoist <- soilDB::uncode(d.cosoilmoist, droplevels = FALSE)`, the month and soimoiststat values are gone. So it looks like there is something going on in `uncode()`. 

I looked at a couple other `get_(something)_from_SDA()` functions and they also seem to have some lost data.

**Comment by brownag** [comment]
I made some progress on this yesterday, and think the primary issue has been resolved at least for `get_cosoilmoist_from_SDA()`. Still thinking on interfaces to new functions for helping with metadta, and need to test the rest of the SDA functions and some more edge cases, see draft PR #254

You can install a development branch with:
```r
remotes::install_github("ncss-tech/soilDB@factorsETC")
```

Would be glad to have you test it out, let me know if you see anything else that is off.

**Comment by monikashea** [comment]
Thanks for fixing this @brownag! The development version is working great now.
