### ISSUE TITLE
Rosetta API sending empty results

### ISSUE THREAD

**Issue by diegodinamarca** [ncss-tech/soilDB#255]
Hello everyone. I'm using soilDB package to predict Field Capacity and Permanent Wilting Point by estimating the Van Genuchten Parameters using the Rosetta function implemented in the package. The data has millions of records so I've been passing the data to the ROSETTA function in chunks. 

The process was like 30% completed but since last weekend I've been getting the same empty result for all the data that I've tested. To my best knowledge the ROSETTA function connects to the Rosetta API, so my first thought was that the cluster that we're running the code activated some firewall that prevented the connection. But that was not the case so we're trying to figure out what the problem is.

Is it posibble that the connection is being blocked on the server side due to the millions of simultanous connections to the API?

**Comment by dylanbeaudette** [comment]
Likely hit a resource limitation, try the local version of the algorithm.

https://github.com/ncss-tech/rosettaPTF

**Comment by diegodinamarca** [comment]
I'll give it a try with that package, thank you both for your answers!

**Comment by brownag** [comment]
The `ROSETTA()` function seems to be functioning normally in tests, and it is expected that a NULL result is returned on API failure (as appears to be the case for your usage).

@diegodinamarca I hope you had some luck running the ROSETTA routines locally with {rosettaPTF}. Please feel free to raise any issues you encountered in the tracker: https://github.com/ncss-tech/rosettaPTF/issues--it is a fairly new package with not many users that I am aware of, so your input is welcome!
