### ISSUE TITLE
Error thrown `missing value where TRUE/FALSE needed`

### ISSUE THREAD

**Issue by morrismc99** [ncss-tech/soilDB#264]
I've been working with soilDB to download data from NRCS SNOTEL sites and received the following error multiple times with a site of interest:

code I ran:
`site_no <- 870

yrs <- seq(1979,2022)df <- fetchSCAN(site.code = site_no,
                year = yrs,
                timeseries = "Daily")`

`Error [site 870]: no lines available in input
multiple sensors per site [site 870] TAVG.D,TAVG.D-2
multiple sensors per site [site 870] TMIN.D,TMIN.D-2
multiple sensors per site [site 870] TMAX.D,TMAX.D-2
multiple sensors per site [site 870] TAVG.D,TAVG.D-2
multiple sensors per site [site 870] TMIN.D,TMIN.D-2
multiple sensors per site [site 870] TMAX.D,TMAX.D-2
multiple sensors per site [site 870] TAVG.D,TAVG.D-2
multiple sensors per site [site 870] TMIN.D,TMIN.D-2
multiple sensors per site [site 870] TMAX.D,TMAX.D-2
multiple sensors per site [site 870] TAVG.D,TAVG.D-2
multiple sensors per site [site 870] TMIN.D,TMIN.D-2
multiple sensors per site [site 870] TMAX.D,TMAX.D-2
multiple sensors per site [site 870] TAVG.D,TAVG.D-2
Error in if (is.null(res$Time) || all(res$Time == "")) { : 
  missing value where TRUE/FALSE needed`

As best I can tell its not an issue with the request I'm making. I know this code was updated recently - perhaps there in lies the problem?

**Comment by brownag** [comment]
Thanks for reporting this! Indeed this was an oversight in recent changes for sub-daily data / ensuring the same columns (i.e. `Time`) are returned regardless of request type.

Above commit 2a807234 should resolve the issue, now I get:

``` r
library(soilDB)

site_no <- 870

yrs <- seq(1979, 2022)
df <- fetchSCAN(site.code = site_no,
                year = yrs,
                timeseries = "Daily")
#> Error [site 870]: no lines available in input
#> multiple sensors per site [site 870] TAVG.D,TAVG.D-2
#> multiple sensors per site [site 870] TMIN.D,TMIN.D-2
#> multiple sensors per site [site 870] TMAX.D,TMAX.D-2
#> multiple sensors per site [site 870] TAVG.D,TAVG.D-2
#> multiple sensors per site [site 870] TMIN.D,TMIN.D-2
#> multiple sensors per site [site 870] TMAX.D,TMAX.D-2
#> multiple sensors per site [site 870] TAVG.D,TAVG.D-2
#> multiple sensors per site [site 870] TMIN.D,TMIN.D-2
#> multiple sensors per site [site 870] TMAX.D,TMAX.D-2
#> multiple sensors per site [site 870] TAVG.D,TAVG.D-2
#> multiple sensors per site [site 870] TMIN.D,TMIN.D-2
#> multiple sensors per site [site 870] TMAX.D,TMAX.D-2
#> multiple sensors per site [site 870] TAVG.D,TAVG.D-2
#> multiple sensors per site [site 870] TMIN.D,TMIN.D-2
#> multiple sensors per site [site 870] TMAX.D,TMAX.D-2
#> 76336 records (3.8 Mb transferred)
```
