### ISSUE TITLE
jsonlite now uses `base::url()` rather than `curl::curl()`

### ISSUE THREAD

**Issue by brownag** [ncss-tech/soilDB#266]
https://github.com/jeroen/jsonlite/commit/8c3afc67b173b754caa621ff31beea1e833e7d9b

jsonlite now uses `base::url()` rather than `curl::curl()` and several functions are now breaking in the CI with jsonlite > 1.8.1 installed.

Reading gzippped JSON from remote URL as is done in `fetchKSSL()` gives errors related to the binary v.s. text result when using "gz" compression:

```
Error in parse_con(txt, bigint_as_char) : 
  lexical error: invalid char in json text.
                                                            (right here) ------^
Calls: fetchKSSL ... <Anonymous> -> parse_and_simplify -> parseJSON -> parse_con
```

Removing `gzip=1` argument from URL still works.

**Comment by brownag** [comment]
Wrapping the URLs in `gzcon(url(...))` does the trick, and is backward compatible with earlier jsonlite versions

**Comment by brownag** [comment]
Wrapping the URLs in `gzcon(url(...))` does the trick, and is backward compatible with earlier jsonlite versions

**Comment by dylanbeaudette** [comment]
Thanks.
