### ISSUE TITLE
basic NA-filling for fetchHenry() / fetchSCAN() / CDEC_query()

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/soilDB#27]
Add an option to each of these functions for *simple* NA-filling by methods from the `zoo` (or similar) package.

Other ideas:
  * https://cran.rstudio.com/web/packages/timetk/vignettes/TK00_Time_Series_Coercion.html

**Comment by brownag** [comment]
This will be addressed in the newer, more specific issue: https://github.com/ncss-tech/soilDB/issues/265
