### ISSUE TITLE
get_soilseries_from_NASISWebReport() returning duplicate columns

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/soilDB#270]
Columns affected: `areasymbol` and `areatypename`. Contents are identical. Seems like a join issue, possible asking for all columns across a couple of tables.

This is in the `get_soilseries_from_NASISWebReport` report.

I can't tell if this is by design or an accident.

```
SECTION                  # adds the data to the report
DATA
USING basic 
soilseriesname, soilseriesstatus, benchmarksoilflag, statsgoflag, 
mlraoffice, areasymbol, areatypename, 
taxclname, taxorder, taxsuborder, taxgrtgroup, taxsubgrp, 
taxpartsize, taxpartsizemod, 
taxminalogy2,
taxceactcl, taxreaction, taxtempcl, 
originyear, establishedyear, soiltaxclasslastupdated, 
soilseriesiid,
areasymbol, areaname, areatypename
.

END SECTION.
```

**Comment by smroecker** [comment]
I'll look this up Tuesday.

**Comment by smroecker** [comment]
I fixed the duplicate column names in NASIS report being used to pull the data. 

On a related note, I noticed that the sister report get_soilseries_fromNASIS() function. Will discuss in another issue.
