### ISSUE TITLE
get_OSD(..., fix_ocr_errors = TRUE) error

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/soilDB#271]
This happens when there is no `$HORIZONS`.
```r
get_OSD("ANCHOR BAY", result = 'json', fix_ocr_errors = TRUE)

# Error in `[.data.frame`(res$HORIZONS[[1]], ocr_cols_color) : 
# undefined columns selected
```

**Comment by brownag** [comment]
I believe this is fixed in https://github.com/ncss-tech/soilDB/commit/70d048c23d60ff15d5ef9f3445cebbcb6aa84f06

**Comment by dylanbeaudette** [comment]
Seems to, I tried with all of the series and no errors or obvious problems. I'll do some more testing beyond this issue, but I think that we are good. Thanks.
