### ISSUE TITLE
`ISSR800.wcs()`: problem with texture grids

### ISSUE THREAD

**Issue by brownag** [ncss-tech/soilDB#275]
It appears that the updated 800m grids on SoilWeb are missing some of the soil texture related variables. 

``` r
library(soilDB)

x <- ISSR800.wcs(
  aoi = list(aoi = c(-114.16, 47.6,-114.15, 47.7),
             crs = 'EPSG:4326'),
  var = 'texture_2550cm'
)
#> Loading required namespace: sf
#> Warning: `C:/Users/Andrew.G.Brown/AppData/Local/Temp/RtmpGmi7Um/
#> file373014297e05' not recognized as a supported file format. (GDAL error 4)
#> Error: [rast] cannot open this file as a SpatRaster: C:/Users/Andrew.G.Brown/AppData/Local/Temp/RtmpGmi7Um/file373014297e05
```

The generated URL returns error "No such file or directory":
```
msWCSGetCoverageMetadata20(): Unable to access file. /data1/website/800m_grids/rasters/texture_2550.tif: No such file or directory
```
http://soilmap2-1.lawr.ucdavis.edu/cgi-bin/mapserv?map=/soilmap2/website/wcs/issr800.map&SERVICE=WCS&VERSION=2.0.1&REQUEST=GetCoverage&COVERAGEID=texture_2550cm&FORMAT=image/tiff&GEOTIFF:COMPRESSION=LZW&SUBSETTINGCRS=EPSG:5070&FORMAT=GEOTIFF_BYTE&SUBSET=x(-1366532.46624416,-1363332.46624416)&SUBSET=y(2864841.07172432,2876041.07172432)&RESOLUTION=x(800)&RESOLUTION=y(800)

**Comment by brownag** [comment]
So--just trying to understand--the old version was deleted but the new one was not added? 

The error is not related to the RAT but rather that the file does not exist on the server.

**Comment by dylanbeaudette** [comment]
The file is in place (as of 10 minutes ago), the RAT is missing. The delay had to do with the major change in the RAT.

**Comment by brownag** [comment]
OK, can confirm the error is now `cannot open URL 'http://soilmap2-1.lawr.ucdavis.edu/800m_grids/RAT/texture_2550.csv': HTTP status was '404 Not Found'`

**Comment by brownag** [comment]
We should have all remote requests failing gracefully in the event that we get an error response--even if it is one we "expect".

The possibility of `read.csv(<URL>)` failing in this function is something I overlooked in the past. This will now return the non-categorical grid with a message. 

However this will not resolve issues with the tests that check that the categories are set as expected.

When you say "major change in the RAT" do you mean something that would cause the test to fail (i.e. a change in the column names)? These functions have been using terra for months so this is a news to me that something changed on the SoilWeb side related to this.

**Comment by dylanbeaudette** [comment]
Agreed, good idea to protect all downloads just in case.

I realized last Friday PM, after converting code from {raster} → {terra} that grids and RATs for the soil texture grids contained cell values within [0, 11]. The {raster}-based approach resulted in cell values in [1, 12]. This broke all manner of things, and I hadn't yet pushed the grids / RATs into their public directory. I'll explain the rest later.

Should be fixed now.
