### ISSUE TITLE
should NASIS query functions target only the selected set?

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/soilDB#29]
Example from `soilDB::get_component_data_from_NASIS_db()`:

```sql
SELECT dmudesc, compname, comppct_r, compkind, majcompflag, localphase, drainagecl, pmgroupname, elev_r, slope_l, slope_r, slope_h, aspectrep, map_r, airtempa_r as maat_r, soiltempa_r as mast_r, reannualprecip_r, ffd_r, tfact, wei, weg, nirrcapcl, nirrcapscl, irrcapcl, irrcapscl, frostact, hydgrp, corcon, corsteel, taxclname, taxorder, taxsuborder, taxgrtgroup, taxsubgrp, taxpartsize, taxpartsizemod, taxceactcl, taxreaction, taxtempcl, taxmoistscl, taxtempregime, soiltaxedition, coiid, dmuiid
  
  FROM 
  datamapunit_View_1 dmu INNER JOIN
  component co ON co.dmuiidref = dmu.dmuiid LEFT OUTER JOIN
  copmgrp ON copmgrp.coiidref = co.coiid AND copmgrp.rvindicator = 1
```

## Discuss
Should queries like these (really, all queries to NASIS) limit selection to the special selected set "views"? Looking over the pedon and component code, I see a mixture of the two styles. There are a few cases where using the base tables (`pedon` vs. `pedon_View_1`)  seems "correct":
   * the first table in the query is joined to a base table via INNER join
   * the base table isn't something that you can adjust via selected set, e.g. `localplant` or `geomorfeattype`

Other than that, there should be systematic use of **one or the other**. Using the base tables can be *handy* when one hasn't fully loaded the selected set. That road leads to inconsistency. I suggest using the selected set--with an option for hitting the base tables via `lazy=TRUE`.

**Comment by dylanbeaudette** [comment]
C/O Stephen on the topic of using a "mixture" of tables / views:

> My vote is for using a mixture, which shouldn’t be surprising since I’m the source of the inconsistency. 
> 
> I settled on this approach after reviewing Jason and Kevin’s NASIS reports, where they use a similar approach by inserting REAL before any table indicate the base table. The idea is you save the user the mental anguish of trying to find just right query to load ALL the data the report needs to function. This road block in a real frustration for a lot of lowly users (Jay excluded). Otherwise we may need to recommend/write soilDB approved queries. I have frequently gotten questions from folks complaining about this, even when soilDB returns a messages indicating which tables are missing. Believe it or not, most folks aren’t great at managing their selected set.
> 
> As long the user’s selected set has say the “datamapunit” table loaded (and assuming their local database has other records loaded), it shouldn’t matter other parts of the query are pointed at the base or selected set “mapunit” tables. Joining on the selected set “datamapunit” table to the mapunit base table will automatically filter out the unnecessary map unit records.
> 
> I’m not sure what is confusing about this approach. Again my experience has been that the concept of the selected set is still confusing to most users.

**Comment by dylanbeaudette** [comment]
An update. I now have a concrete example of how the "mixed" use of selected set and entire local DB are causing problems. Consider the situation where you have components that aren't needed / wanted in an analysis and they are manually removed from the selected set. `fetchNASIS_component_data()` would bring in all component records.

I have changed [NASIS component queries](https://github.com/ncss-tech/soilDB/commit/bc4836917acb982cb9d8c879ae6613e504779134) to hit only the selected set views.

While I don't foresee this kind of problem happening with the pedon data, I still think that functions returning data from NASIS should be specific: selected set *or* entire local database.

**Comment by smroecker** [comment]
Couldn't you also just switch the order of the joins, such that the component_View_1 is listed first?

FROM
component_View_1 co INNER JOIN
datamapunit dmu ON dmu.dmuiid = co.dmuiidref LEFT OUTER JOIN
 copmgrp ON copmgrp.coiidref = co.coiid

WHERE copmgrp_View_1.rvindicator = 1

**Comment by dylanbeaudette** [comment]
True. 

I would suggest that clever SQL contortions aside, we should strive for concise queries that can be programmatically toggled between the selected set and "everything".

How about the proposed SQL style:

```sql
SELECT [...]
FROM
datamapunit_View_1 AS dmu
LEFT OUTER JOIN component_View_1 AS co  ON dmu.dmuiid = co.dmuiidref 
LEFT OUTER JOIN copmgrp_View_1 AS cpmg ON cpmg.coiidref = co.coiid
WHERE cpmg.rvindicator = 1
[...]
```

Such that:
  * the string `_View_1` can be replaced with an empty string when asking for the entire local DB
  * the string `_View_1` is used as few times as possible thanks to table aliases
  * tables are joined from the "top down" such that parent/child relationships are mostly obvious

A reasonable style guide might help keep the queries from getting overly complex and make reading other people's code simpler.

![image](https://user-images.githubusercontent.com/624277/32305346-47f0696a-bf32-11e7-8f6b-a4335d0689ce.png)

**Comment by dylanbeaudette** [comment]
Implemented in:
  * component records: 036080eac9f6b608146f65757b41367d27d5f968
  * pedon records: 0e6ad93534e8f58d10754c28d1ff272dde41854b
