### ISSUE TITLE
`get_SDA_*` functions should return "ID"/mukey value in first column

### ISSUE THREAD

**Issue by brownag** [ncss-tech/soilDB#291]
- This will change the default column order such that the unique ID column is always the first in the result data.frame
- For aggregation `method="none"` `mukey` will be followed by `cokey` (and `chkey` if applicable), and then the legend/mapunit level identifying information

This shouldn't break anything, but will make applying sets of categorical values to e.g. `mukey.wcs()` categorical SpatRaster output easier (no subsetting of columns or reordering required)

**Comment by dylanbeaudette** [comment]
Yes, thanks. Good idea.
