### ISSUE TITLE
mirror WCS across SoilWeb servers

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/soilDB#309]
Now that the WCS is getting more frequent use, best to mirror across servers and expose on load-balancer.

- [x] WCS configuration files
- [x] mukey grids
- [x] soil color grids
- [x] ISSR800 source data
- [x] add required URLs to load balancer

**Comment by brownag** [comment]
Related to this: `ISSR800()` should gracefully handle failure of retrieving the RAT. Currently it is breaking tests after the grid is downloaded.
