### ISSUE TITLE
use of aqp::rgb2munsell() in soilDB

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/soilDB#318]
I'm about to push aqp 2.0.2 out which will start the transition from `rgb2munsell()` → `col2Munsell()`. I've made this change to all aqp functions and documentation. Prior to aqp 2.1 a message will be issued when `rgb2munsell()` is called, after that it will be deprecated. `col2Munsell()` is a more generalized version with better error trapping, and eventually, better documentation than `rgb2munsell()`.

I've added some TODOs in soilDB as reminders to myself, once aqp 2.0.2 is on CRAN.

[related issue in aqp](https://github.com/ncss-tech/aqp/issues/297)

**Comment by brownag** [comment]
closed by #325
