### ISSUE TITLE
SDA_spatialQuery failing

### ISSUE THREAD

**Issue by potash** [ncss-tech/soilDB#349]
I have a job that I run regularly that calls `SDA_spatialQuery()`. The function is currently failing for many different shapefiles returning

```
[1] "Error : lexical error: invalid char in json text.\n                                       <!DOCTYPE html>  <html lang=\"en\n                     (right here) ------^\n\n"
attr(,"class")
[1] "try-error"
attr(,"condition")
<simpleError: lexical error: invalid char in json text.
                                       <!DOCTYPE html>  <html lang="en
                     (right here) ------^
```

**Comment by brownag** [comment]
Hi @potash 

It seems that the https://sdmdataaccess.sc.egov.usda.gov/tabular/post.rest API endpoint is was down for a couple hours today, and also not throwing an actual error as the status, hence the issue parsing the HTML (which should be a JSON response).

It seems like it is working again--as of a couple minutes ago

**Comment by potash** [comment]
Thanks @brownag, can confirm it is working now. Closing the issue.
