### ISSUE TITLE
switch to WGS84 coordinates when querying NASIS pedons

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/soilDB#41]
`get_site_data_from_NASIS_db()`

**Comment by brownag** [comment]
We return standard WGS84 latitude longitude in `y_std` and `x_std` columns. 

``` r
colnames(soilDB::get_site_data_from_NASIS_db())
#> Loading required namespace: odbc
#>  [1] "siteiid"            "peiid"              "site_id"           
#>  [4] "pedon_id"           "obs_date"           "utmzone"           
#>  [7] "utmeasting"         "utmnorthing"        "x"                 
#> [10] "y"                  "horizdatnm"         "x_std"             
#> [13] "y_std"              "gpspositionalerror" "describer"         
#> [16] "pedonpurpose"       "pedontype"          "pedlabsampnum"     
#> [19] "labdatadescflag"    "tsectstopnum"       "tsectinterval"     
#> [22] "utransectid"        "tsectkind"          "tsectselmeth"      
#> [25] "elev_field"         "slope_field"        "aspect_field"      
#> [28] "plantassocnm"       "earthcovkind1"      "earthcovkind2"     
#> [31] "erocl"              "bedrckdepth"        "bedrckkind"        
#> [34] "bedrckhardness"     "hillslopeprof"      "geomslopeseg"      
#> [37] "shapeacross"        "shapedown"          "slopecomplex"      
#> [40] "drainagecl"         "flodfreqcl"         "floddurcl"         
#> [43] "flodmonthbeg"       "pondfreqcl"         "ponddurcl"         
#> [46] "pondmonthbeg"       "geomposhill"        "geomposmntn"       
#> [49] "geompostrce"        "geomposflats"       "swaterdepth"       
#> [52] "slope_shape"
```

These should generally be equivalent to `x` and `y` (I believe), but they do suffer from rounding issues. 

``` r
res <- (soilDB::get_site_data_from_NASIS_db())
#> Loading required namespace: odbc
testthat::expect_equal(res$x_std, res$x)
#> Error: res$x_std not equal to res$x.
#> 103/105 mismatches (average diff: 2.9e-06)
#> [1] -120 - -120 == -1.03e-05
#> [2] -120 - -120 == -2.83e-06
#> [3] -120 - -120 == -4.88e-06
#> [4] -120 - -120 ==  1.64e-06
#> [5] -120 - -120 ==  1.84e-06
#> [6] -120 - -120 ==  5.20e-06
#> [7] -120 - -120 == -3.52e-07
#> [8] -120 - -120 == -1.85e-06
#> [9] -120 - -120 == -7.58e-06
#> ...
```

On this topic of standard coordinates and which columns should be used preferentially... I think we can probably get rid of the message produced by `fetchNASIS` when multiple UTM zones exist in the site data. 

e.g.
> multiple horizontal datums present, consider using WGS84 coordinates (x_std, y_std)

**Comment by brownag** [comment]
I think this issue can be closed considering the calculated x/y from DMS components (in whatever datum), UTM and standard WGS84 decimal degrees are returned as separate columns in fetchNASIS result. To clarify my above comments I would say users should strive to have WGS84 decimal degrees (x_std, y_std) populated for all sites with coordinate information--and use them _exclusively_. 

WGS84 decimal degrees are the preferred, required format for location data in NASIS. 

- Use calculations in NASIS to derive WGS84 decimal degrees if the only known data are in a different format such as NAD27 DMS, NAD83 DMS or WGS84 DMS. 
- 
- If only UTM are available, use "Convert UTM to Latitude/Longitude" then "Convert WGS84 Latitude/Longitude to Decimal Degrees"
