### ISSUE TITLE
NASIS lab data functions aren't working as expected

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/soilDB#44]
Do we need all three functions?
   * `get_phlabresults_data_from_NASIS_db()`
   * `get_labpedon_data_from_NASIS_db()`
   * `get_lablayer_data_from_NASIS_db()`

TODO:
   * review SQL
   * wt. mean code for multiple samples / hz needs to be simplified
   * what about samples that don't fit cleanly within a single horizon?
   * why do some queries return all NA?
   * documentation

**Comment by jskovlin** [comment]
Some queries return all NA because there are all NA rows in the phlabresults table that exist in NASIS.  Not sure why this is the case and what may have created that.  I added some code to the very end of the function to remove any all NA rows.

**Comment by smroecker** [comment]
The get_phlabresults_data_from_NASIS_db() functon could be demoted to internal use only (e.g.  .get_phlabresults_data_from_NASIS_db()), by get_horizon_data_from_NASIS_db(). I'll get on that, and then close this issue.

The others pull the site and horizons tables for the NCSS lab pedon tables in NASIS. Should probably improve their help files. Will get on that also. :)

**Comment by brownag** [comment]
closed per stephen's recent updates
