### ISSUE TITLE
profiling: fetchNASIS_pedons()

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/soilDB#55]
Adding to misc/ dir of package. Initial results can be seen [here](http://ncss-tech.github.io/soilDB/misc/fetchNASIS_pedons-flame-graph.svg).

It looks like `simplifyFragmentData` could use some work.

**Comment by brownag** [comment]
I like these flame graphs. 

I was surprised to see simplifyFragmentData so prevalent here (~42.5%)... always figured it was the simplifyColorData (only 12.6%) that made this function hang up with bigger datasets.

**Comment by dylanbeaudette** [comment]
After the [latest fixes](https://github.com/ncss-tech/soilDB/commit/8e6b0d389df5302d4c8823c7281c18d511628061) applied to `simplifyFragmentData`, this function now contributes much less to the overall time.

   * http://ncss-tech.github.io/soilDB/misc/fetchNASIS_pedons-flame-graph.svg
   * http://ncss-tech.github.io/soilDB/misc/fetchNASIS_pedons-flame-graph-time.svg

`simplifyColorData` is now one of the top offenders. It seems that we are running into `ddply`-related lag when there are > 500 or so pedons.

It is not clear if unexported functions like `.formatLandformString` are named in the results.

**Comment by dylanbeaudette** [comment]
Significant progress after conversion from `ddply` &rarr; `aggregate` in `simplifyFragmentData` as of 
02ea69d79b2575e25ef6d77ebc8d800877aff2c7

![image](https://user-images.githubusercontent.com/624277/52003755-42fd0900-247a-11e9-9ac0-bc07c1b187a4.png)

**Comment by dylanbeaudette** [comment]
Significant progress related to `simplifyColorData` via #88. 
![image](https://user-images.githubusercontent.com/624277/52022334-4b226c00-24ad-11e9-8946-9670a54b65a1.png)

**Comment by dylanbeaudette** [comment]
This is likely one of the worst offenders:
`best.tax.data <- ddply(extended_data$taxhistory, 'peiid', .pickBestTaxHistory)`

Conversion to `split` / `lapply` saves 10 seconds on ~ 4k pedons.

**Comment by dylanbeaudette** [comment]
Changes applied and results:
   * ~ 4k pedons in local database SS => 80 seconds (slow simplifyColorData)
   * ~ 4k pedons in local database SS => 44 seconds (fast simplifyColorData)
   * ~ 4k pedons in local database SS => 32 seconds (lapply() .pickBestTaxHistory)
   * ~ 4k pedons in local database SS => 30 seconds (stringsAsFactors=FALSE for taxhistory uncode())
   * ~ 4k pedons in local database SS => 30 seconds (lapply() .formatLandformString)

Comparing before / after suggests data are unchanged.

**Comment by dylanbeaudette** [comment]
I'll leave all remaining optimization to the `plyr` &rarr; `base` conversion at some future date
