### ISSUE TITLE
multiple texture classes per horizon

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/soilDB#6]
how should multiple textures be dealt with? (2 rows/hz are currently returned)
- can this be fixed in SQL ?
-  NASIS: we are keeping only the first record
-  PedonPC: texture class is ommited from query

**Comment by brownag** [comment]
There is a standard way of flattening this that is used in NASIS. 

For instance, a snippet from `get_hz_data_from_NASIS_db()`

```sql
SELECT phiidref, MIN(texcl) AS texcl, MIN(lieutex) as lieutex
```

The NASIS 7 metadata domains of `texcl` and `lieutex` are coded such that the coarsest textures are returned in the case of multiple records in `phtexture`

**Comment by brownag** [comment]
#52
