### ISSUE TITLE
unify methods / assumptions for flattening parent material and geomorphic records

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/soilDB#60]
There are three distinct functions for *flattening* the incredibly complex parent material and geomorphic records:

   * local NASIS pedons `.formatLandformString`
   * local NASIS components `.formatcoLandformString`
   * SDA components `.cogmd_prep`

Details in [utils.R](https://github.com/ncss-tech/soilDB/blob/master/R/utils.R).

Unification (if possible) would at least help when cross-referencing pedons with components or local NASIS with SDA. We likely need to dedicate a couple of hours to discuss, plan, and test.

**Comment by brownag** [comment]
Closed because https://github.com/ncss-tech/soilDB/issues/84 is a now resolved, more comprehensive version of this issue.
