### ISSUE TITLE
gSSURGO.chunk.rda is very old and associated tutorial is now incorrect

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/soilDB#62]
Time to replace it with a recent copy and re-write / revise the tutorial:

http://ncss-tech.github.io/AQP/soilDB/gSSURGO-SDA.html

**Comment by dylanbeaudette** [comment]
removed due to note from CRAN lords

**Comment by MatthieuStigler** [comment]
Hi

is there an updated/corrected version of this tutorial? 

Thanks!

**Comment by dylanbeaudette** [comment]
Thanks for the positive feedback. I'd like to update this tutorial, but don't have much time to work on it right now. I'd suggest looking at the gSSURGO toolbox for a quick solution in ArcGIS.

https://www.nrcs.usda.gov/wps/portal/nrcs/detail/soils/home/?cid=nrcs142p2_053628#tools

I'm planning on making some gSSURGO chunks available (but not in soiDB) for a revised tutorial. All of this hinges on an efficient method for extracting / posting / documenting the integer grid of map units keys that is stored inside of gSSURGO. A stand-alone copy of these data would make interactions with gSSURGO a heck of a lot simpler.

**Comment by MatthieuStigler** [comment]
ay Dylan, you are the small light of hope in the darkness of the SSURGO ArcGis world, if you now start recommending ArcGIS, it's the end of the world! Don't forget that the biggest improvement to SSURGO would be just to make it more accessible, it's a beautiful dataset in a horrible format. 

Anyway, for the purpose of examples in soilDB, having a very small built-in raster of SSURGO should be quite light?

Thanks again

**Comment by dylanbeaudette** [comment]
> a quick solution in ArcGIS
Yes, I know. I think that I threw up a little after typing that.

Speaking of gSSURGO: what kind of task are you performing? Is it something that can be done with SDA?

**Comment by brownag** [comment]
> Anyway, for the purpose of examples in soilDB, having a very small built-in raster of SSURGO should be quite light?

So far, soilDB does not have any raster processing capabilities, and we don't presently have plans to implement them. A raster representation equivalent to gSSURGO could be created from the `soilDB::fetchSDA_spatial()` result with your favorite rasterizing function. 

But we won't be importing/storing `RasterLayer` (or any other variant of raster object) .Rdas or .tifs within the soilDB package itself. 

We can certainly provide links to the sample data sets Dylan mentions above via GitHub.

**Comment by dylanbeaudette** [comment]
@MatthieuStigler: the {sf} library can read tables / features from the FGDB file. I'll work with @smroecker (who has done some great work with gSSURGO in R) to make a couple of examples. Thanks for the reminder.

**Comment by MatthieuStigler** [comment]
@dylanbeaudette _what kind of tasks_: well I was using `soilDB` to explore and understand gSSURGO, which is why having access to a small example of gSSURGO in the tutorial was welcome
@brownag _no import of raster capabilities_: I see your point. For a user perspective, I was keen to be able to compare with a gSSURGO example. Even if `soilDB` has no raster capabilities, still storing a very small gSSURGO raster in `/inst`, to be called with `system.file()` and called within a `if(require())` could be a very light change to package (a 12x12 raster seems to be 1KB, and only needs a `Suggests` in DESCRIPTION) could be useful for some users? Happy to pull request that.
@dylanbeaudette  _add couple of examples_: that would be very welcome, yes! As per my understanding, we are still with the paradox that in R, we can extract tables and polygons (!) from the gSSURGO gdb monster, still no raster yet, is that correct?

Thanks to both for your inputs!!

**Comment by brownag** [comment]
> @dylanbeaudette _what kind of tasks_: well I was using `soilDB` to explore and understand gSSURGO, which is why having access to a small example of gSSURGO in the tutorial was welcome
> @brownag _no import of raster capabilities_: I see your point. For a user perspective, I was keen to be able to compare with a gSSURGO example. Even if `soilDB` has no raster capabilities, still storing a very small gSSURGO raster in `/inst`, to be called with `system.file()` and called within a `if(require())` could be a very light change to package (a 12x12 raster seems to be 1KB, and only needs a `Suggests` in DESCRIPTION) could be useful for some users? Happy to pull request that.
> @dylanbeaudette _add couple of examples_: that would be very welcome, yes! As per my understanding, we are still with the paradox that in R, we can extract tables and polygons (!) from the gSSURGO gdb monster, still no raster yet, is that correct?
> 
> Thanks to both for your inputs!!

I am definitely not opposed to having raster in Suggests -- perhaps we can work this out, and there will be a place for raster in future soilDB capabilities (say, to fetch the gridded SSURGO derivatives @dylanbeaudette mentioned for a user-specified extent from a yet-to-be-created NCSS web service)

Another option would be to move gSSURGO related things over to **sharpshootR** https://github.com/ncss-tech/sharpshootR -- our package for high-level visualization/convenience functions -- where raster processing/visualization is a bit more "natural" of a fit -- and raster is already in Suggests!
