### ISSUE TITLE
simplifyFragmentData - unusual aggregation behavior

### ISSUE THREAD

**Issue by brownag** [ncss-tech/soilDB#70]
On Julie's machine, rock fragment volume sums within classes returned by simplifyFragmentData() were not correct.

Stepping through the code... the data in NASIS were correctly populated, and the code to sort fragment records into size classes and sum within classes is working correctly. 

The problem arises when going from long->wide (1 record per horizon with frags) via the reshape2::dcast() call. 
```
rf.wide <- reshape2::dcast(rf.sums, fm, value.var = "volume", drop = FALSE)
```

A warning printed to the console about the default aggregation (length) function being used led me to try using `fun.aggregate=sum` in the dcast() call, which solved the problem. However, presumably, the sums have already been calculated via:

```
rf.sums <- ddply(rf.classes, c(id.var, "class"), plyr::summarise, volume = sum(fragvol, na.rm = TRUE))
```

Has something changed in reshape2? Has the default aggregation always been length??
I have been unable to replicate the error condition on my machine. Instead of correct volumetric sums, integer values between 1 and 5 were being returned after conversion from long->wide format. Could these numbers be the lengths (number of records contributing) to the "sum" for each class rather than the sum itself?

**Comment by brownag** [comment]
This issue cropped up on my machine this week. I was in the middle of something so I just fixed it by installing the "agb" branch with the above mentioned fix.

Is anyone else having this issue?

**Comment by dylanbeaudette** [comment]
Thanks for reporting this. The default behavior of reshape2::dcast has always bothered me: there are few cases where a warning + change in behavior is a good idea. Do you have some examples that I could check? I'll use this as the basis for the first soilDB test suite element.

I suspect that the problem may be related to duplication with respect to `id` and `class`, or something I have overlooked. Again, an example pedon ID would be really helpful.

**Comment by dylanbeaudette** [comment]
There were several issues that may have been contributing to the unusual and hard to replicate data:
   * `NA` in the fragment volume
   * `NA` in all of the fragment size (RV, and high)
   * bug in `.sieve()` by which 'para' was being added to 'NA' to create a bogus fragment size class

These were all accounted for in e2b237d87554fc9c79c87310661909f87fe91ad5.

This commit comes with a slight change in behavior: records with NA `fragvol` are removed before `simplifyFragmentData()` does anything. A warning is generated if this happens.

This commit addresses an issue in #43: `simplfyFragmentData` has been renamed to `simplifyFragmentData`, with a stub pointing to the old function name for backwards compatibility.

**Comment by dylanbeaudette** [comment]
After some more testing, I no longer see the warning message from `dcast`. I think we can close this issue now.

Reminder to future self: don't trust `dcast` to always do the right thing, consider  an aggregation function that throws an error.
