### ISSUE TITLE
Restriction depths

### ISSUE THREAD

**Issue by phytoclast** [ncss-tech/soilDB#77]
The current fetchNASIS function doesn't report restriction depths. While sometimes the presence of bedrock is indicated by a horizon designation, and the bulk density may imply a dense till layer, it is not clear how consistent these data are populated. Other restrictions like ortstein or fragipans may not be detectable via texture and density alone.

**Comment by dylanbeaudette** [comment]
Things like diagnostic features and restrictions are somewhat difficult to flatten into the structure returned by `fetchNASIS`. Note that diagnostic horizon data are loaded when querying the pedon data. I just added this functionality to the component data query (b5605fe270c737d5c3c50c9b07f7b4f79a7fc927).

Two options for the restrictive features:
  1. make a new "extended" query (similar to pedon data) that gets the restrictive features as a `data.frame` that would have to be post-processed and joined to the SPC from `fetchNASIS`

2. use `getSoilDepthClass` which estimates soil depth based on REGEX pattern-matching of horizon designations, see below

```r
# get component data
x <- fetchNASIS(from='components')
# estimate depth class
# adjust restrictive feature REGEX accordingly
d <- getSoilDepthClass(x, top='hzdept_r', bottom='hzdepb_r', name='hzname', p='R|Cr|Cd|qm')
# splice back into SPC
site(x) <- d
 ```

**Comment by brownag** [comment]
@phytoclast @dylanbeaudette 

Recent changes to aqp so SoilProfileCollectionsnow support the use of a @restrictions slot  (get/set using `restrictions()`) -- analagous to diagnostics slot.

`fetchNASIS_pedons()` and `fetchNASIS_components()` now populate the restrictions slot when run against the local database.
