### ISSUE TITLE
Hydric soil indicator

### ISSUE THREAD

**Issue by phytoclast** [ncss-tech/soilDB#78]
The current fetchNASIS and get_component_data_from_NASIS_db functions do not return the hydric status of the component, which is critical to determine whether the soil is a wetland soil. Soil taxonomy and drainage class are insufficient information to determine whether the soil is associated with wetlands. Many soils with an aquic moisture regime are not hydric depending on the depth of moisture control section. Similarly, some poorly drained soils are not considered hydric, depending on a state specific definition of drainage class. In contrast, hydric soils are defined by nationwide standards based on depths of redoximorphic features from the surface, not control sections, and not varying by state.

**Comment by phytoclast** [comment]
Look like just adding the term 'hydricrating' to line 65 in get_component_data_from_NASIS_db.R 
q <- "SELECT dmudesc, compname, comppct_r, compkind, majcompflag, localphase, drainagecl, elev_l, elev_r, elev_h, slope_l, slope_r, slope_h, aspectccwise, aspectrep, aspectcwise, map_l, map_r, map_h, airtempa_l as maat_l, airtempa_r as maat_r, airtempa_h as maat_h, soiltempa_r as mast_r, reannualprecip_r, ffd_l, ffd_r, ffd_h, tfact, wei, weg, nirrcapcl, nirrcapscl, nirrcapunit, irrcapcl, irrcapscl, irrcapunit, frostact, **hydricrating,** hydgrp, corcon, corsteel, taxclname, taxorder, taxsuborder, taxgrtgroup, taxsubgrp, taxpartsize, taxpartsizemod, taxceactcl, taxreaction, taxtempcl, taxmoistscl, taxtempregime, soiltaxedition, coiid, dmuiid

**Comment by dylanbeaudette** [comment]
Great, thanks for the suggested edits.  Done as of 45f02836066ff66ae2d29cf3c4c2a9db0deef70f.
