### ISSUE TITLE
soil texture plotting / subsetting / flagging helper function or guidance

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/soilDB#8]

**Comment by brownag** [comment]
This old issue might be a good fit for leveraging the relatively new functionality in {aqp} for soil texture designed by @smroecker and @dylanbeaudette. 

Could leverage for instance: `aqp::ssc_to_texcl`, `aqp::soilTextureLevels` and the lookup table in aqp: `soiltexture` https://github.com/ncss-tech/aqp/issues/141

I think I would encourage writing this helper function in a generic way that could go into {aqp}. If it has a lot of plotting-related dependencies, perhaps {sharpshootR}? But not soilDB. Thoughts?
