### ISSUE TITLE
add NaF pH to fetchNASIS

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/soilDB#90]

**Comment by brownag** [comment]
I'm not sure that this should come through fetchNASIS by default unless we allow an option for including a list of arbitrary column names from phlabresults. Surely if we allow NaF pH we should allow a way to get other things.


The data are currently accessible by doing a horizon-level join to the pedon horizon lab results. e.g.  `soilDB::get_phlabresults_data_from_NASIS_db()$phnaf_lab`

I agree that there are not easy-enough ways to augment a SPCs horizon level data. 
See https://github.com/ncss-tech/aqp/issues/82

**Comment by dylanbeaudette** [comment]
Maybe we need to approach this in two ways:

   1. better documentation / testing of `get_phlabresults_data_from_NASIS_db()`
   2. implement [nccs-tech/aqp#82](https://github.com/ncss-tech/aqp/issues/82)

The second option is going to break existing code, we need to plan for that.

**Comment by brownag** [comment]
This functionality has been implemented for a while -- fetchNASIS(lab=TRUE) will join the get_phlabresults_data_from_NASIS_db() result into the horizon slot.
