### ISSUE TITLE
fetchNASIS_components() -- qc object refreshing

### ISSUE THREAD

**Issue by brownag** [ncss-tech/soilDB#92]
Make sure that `fetchNASIS_components()` updates the QC (coiids to check) objects stored in `soilDB.env` when no errors are found.

I fixed the only error on the CA729 legend, and the QC error output persisted until i manually cleared `soilDB.env`

I remember I implemented this fix... because they were all not working. The code needs to be reviewed for NASIS components at a minimum

**Comment by dylanbeaudette** [comment]
What do you think, `fetchNASIS` dumps `soilDB.env` vars first off?

**Comment by brownag** [comment]
Added code to fetchNASIS_components to dump the contents of the environment var beforehand
