### ISSUE TITLE
fetchOSD and related functions should return series names in title case

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/soilDB#95]
```r
tools::toTitleCase
```

Possibly change the API: 
https://stackoverflow.com/questions/6176057/convert-all-records-in-postgres-to-titlecase-first-letter-uppercase

**Comment by brownag** [comment]
`get_OSD()` and the SoilKnowledgeBase OSD JSON files also return series names in all caps. I added a TODO to switch series names to title case. (https://github.com/ncss-tech/SoilKnowledgeBase/issues/25; see for example https://github.com/ncss-tech/SoilKnowledgeBase/blob/main/inst/extdata/OSD/E/ECKRANT.json) 

However this change strikes me as something that could wind up causing problems with backward compatibility. I am pretty used to these returning series name in all caps. And the file names are in all caps.
