### ISSUE TITLE
SDA_query & stringsAsFactors

### ISSUE THREAD

**Issue by smroecker** [ncss-tech/soilDB#96]
Currently when a query submitted to SDA_query() fails, it overrides the stringsAsFactors options default. For example:
mu_sda <- get_mapunit_from_SDA(WHERE = "areasymbol = 'IN'")

This is do to line 20 not being reset by line 73 when the function terminates early.
20 opt.original <- options(stringsAsFactors = FALSE)
73 options(opt.original)

I suggest removing line 20 and appending stringsAsFactors = FALSE to line 51.
51 r.content <- httr::content(r, as = 'text', encoding = 'UTF-8')

This appears to fix the issue. I didn't see any other places for line 20 was necessary.

**Comment by brownag** [comment]
Looks like `stringsAsFactors = FALSE` is already hardcoded into `.post_process_SDA_result_set()` -- I am not sure that `options()` code even comes close to doing what it intends to do. Is it a relic of some code long forgotten?

And [nobody asked me, but] I personally think there should be no programmatic changing of `options()` by functions provided by a library... especially if they don't clean up after themselves!

**Comment by dylanbeaudette** [comment]
Thanks guys for pointing all of this out. Short answer: `SDA_query` has evolved over the years to accommodate the various output formats and interfaces to the web-service. As such, there are some vestigial remnants.

I have removed all calls to `options()` in the affected functions. Everything comes back from SDA/JSON as characters. We use `read.table` for type guessing/conversion, strings are not converted to factors per hard-coded logic. Factors can be set later on as needed.
