### ISSUE TITLE
fetchNASIS_components - fails if no components have horizon data

### ISSUE THREAD

**Issue by brownag** [ncss-tech/soilDB#98]
When your selected set / local DB (`SS = FALSE`) is filled only with components that have no horizon dat (e.g. all miscellaneous areas) the following command:
```
component <- fetchNASIS_components(stringsAsFactors = FALSE, fill=TRUE)
```

Results in

> Error: replacement horizon IDs must have same length as original

_**Philosophical question: Should you be able to create an SPC that has no horizon data _at all_?**_

**Comment by brownag** [comment]
@dylanbeaudette

**Comment by brownag** [comment]
Error message should be more informative. No need to return an SPC with no horizon data.

**Comment by brownag** [comment]
Also should trap error with this code
```
component <- fetchNASIS_components(stringsAsFactors = FALSE)
```
`Error in which(f.chorizon.test$hz_logic_pass) :   argument to 'which' is not logical`

**Comment by dylanbeaudette** [comment]
Agreed. Errors need to be more informative when things break, and, a `SoilProfileCollection` with no horizon data is pointless.

@brownag feel free to "fix" these things if you have time. I won't likely be available for `soilDB` work until next week.

**Comment by brownag** [comment]
fixed

**Comment by brownag** [comment]
When called on a selected set containing only Rock outcrop components: ;

```
> soilDB::fetchNASIS_components()
Error in soilDB::fetchNASIS_components() : 
  No horizon data in NASIS component query result.
```
